const questions = [
{ q: "SI unit of electric charge is", o: ["Ampere", "Coulomb", "Volt", "Ohm"], a: 1 },
{ q: "Smallest measurable charge is equal to", o: ["1 C", "1.6 × 10⁻¹⁹ C", "3.2 × 10⁻¹⁹ C", "9.1 × 10⁻³¹ C"], a: 1 },
{ q: "Electric charge is", o: ["Continuous", "Quantized", "Variable", "Imaginary"], a: 1 },
{ q: "Charge of an electron is", o: ["+1.6 × 10⁻¹⁹ C", "–1.6 × 10⁻¹⁹ C", "Zero", "–9.1 × 10⁻³¹ C"], a: 1 },
{ q: "Coulomb’s law is valid for", o: ["Stationary charges", "Moving charges", "Current", "Magnetic fields"], a: 0 },
{ q: "Coulomb’s law force is proportional to", o: ["Product of charges", "Inverse square of distance", "Both A and B", "Sum of charges"], a: 2 },
{ q: "The electrostatic force is", o: ["Weakest force", "Short range", "Long range", "Non-conservative"], a: 2 },
{ q: "Value of Coulomb’s constant (k) is", o: ["9 × 10⁹ N m²/C²", "9 × 10⁻⁹ N m²/C²", "1 × 10⁹ N m²/C²", "8.85 × 10⁻¹² N m²/C²"], a: 0 },
{ q: "Relative permittivity of vacuum is", o: ["1", "0", "9", "∞"], a: 0 },
{ q: "Force between two charges in a medium is", o: ["Same as vacuum", "Increased", "Decreased", "Zero"], a: 2 },
{ q: "Electric field is defined as", o: ["Force × charge", "Force / charge", "Charge × distance", "Potential / charge"], a: 1 },
{ q: "SI unit of electric field is", o: ["N/C", "V/m", "Both A and B", "J/C"], a: 2 },
{ q: "Electric field is a", o: ["Scalar quantity", "Vector quantity", "Tensor", "Dimensionless quantity"], a: 1 },
{ q: "Direction of electric field is defined as direction of force on", o: ["Negative test charge", "Positive test charge", "Any charge", "Electron"], a: 1 },
{ q: "Electric field due to a point charge varies as", o: ["1/r", "1/r²", "r²", "r"], a: 1 },
{ q: "Electric field lines start from", o: ["Negative charge", "Positive charge", "Both charges", "Neutral point"], a: 1 },
{ q: "Electric field lines end on", o: ["Positive charge", "Negative charge", "Neutral point", "Infinity only"], a: 1 },
{ q: "Electric field lines never intersect because", o: ["Charge is conserved", "Field has unique direction", "Field is scalar", "Force is zero"], a: 1 },
{ q: "Number of electric field lines is proportional to", o: ["Distance", "Charge magnitude", "Mass", "Time"], a: 1 },
{ q: "Electric field inside a conductor in electrostatic equilibrium is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "Excess charge on a conductor resides on", o: ["Volume", "Inner surface", "Outer surface", "Center"], a: 2 },
{ q: "Electric field just outside a conductor is", o: ["Zero", "Parallel to surface", "Perpendicular to surface", "Random"], a: 2 },
{ q: "Electric flux is a", o: ["Vector quantity", "Scalar quantity", "Tensor", "Imaginary"], a: 1 },
{ q: "Electric flux through a surface is defined as", o: ["E × A", "E · A", "E / A", "A / E"], a: 1 },
{ q: "SI unit of electric flux is", o: ["N/C", "N·m²/C", "V/m", "C/m²"], a: 1 },
{ q: "Gauss’s law relates electric flux to", o: ["Electric field", "Charge enclosed", "Distance", "Area"], a: 1 },
{ q: "Mathematical form of Gauss’s law is", o: ["∮E·dA = Q/ε₀", "E = F/q", "F = kq₁q₂/r²", "V = IR"], a: 0 },
{ q: "Gauss’s law is applicable for", o: ["Any closed surface", "Only spherical surfaces", "Only cubic surfaces", "Only conductors"], a: 0 },
{ q: "Electric field due to infinite plane sheet is", o: ["Zero", "Depends on distance", "Constant", "Inverse square"], a: 2 },
{ q: "Electric field near an infinite charged sheet is", o: ["σ/ε₀", "σ/2ε₀", "2σ/ε₀", "σ²/ε₀"], a: 1 },
{ q: "Electric field inside a uniformly charged spherical shell is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "Electric field outside a charged spherical shell behaves like", o: ["Uniform field", "Field of a point charge", "Zero field", "Magnetic field"], a: 1 },
{ q: "Electric dipole consists of", o: ["Two unlike charges equal in magnitude", "Two like charges", "Three charges", "One charge"], a: 0 },
{ q: "Dipole moment is defined as", o: ["q/r", "q × r", "q²", "r²"], a: 1 },
{ q: "SI unit of dipole moment is", o: ["C", "C·m", "N·m", "J"], a: 1 },
{ q: "Direction of dipole moment is from", o: ["–q to +q", "+q to –q", "Centre outward", "Random"], a: 0 },
{ q: "Torque on an electric dipole in uniform field is maximum when angle is", o: ["0°", "30°", "60°", "90°"], a: 3 },
{ q: "Torque on dipole in uniform field is zero when angle is", o: ["90°", "60°", "45°", "0°"], a: 3 },
{ q: "Potential energy of dipole is minimum when dipole is", o: ["Perpendicular to field", "Anti-parallel to field", "Parallel to field", "Random"], a: 2 },
{ q: "Electric field lines for a dipole", o: ["Are closed loops", "Start and end on same charge", "Start on + and end on –", "Are circular"], a: 2 },
{ q: "Gaussian surface is", o: ["Always spherical", "Imaginary closed surface", "Physical surface", "Conductor only"], a: 1 },
{ q: "Flux through a closed surface depends on", o: ["Shape", "Size", "Charge enclosed", "Area"], a: 2 },
{ q: "Net electric flux through a closed surface with no charge inside is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "Electrostatic force is conservative because", o: ["Path independent work", "Depends on distance", "Acts at rest", "Is strong"], a: 0 },
{ q: "Coulomb’s law is inverse square law similar to", o: ["Magnetic force", "Gravitational force", "Nuclear force", "Friction"], a: 1 },
{ q: "If distance between two charges is doubled, force becomes", o: ["Double", "Half", "One-fourth", "Four times"], a: 2 },
{ q: "Electric field due to a charged conductor", o: ["Exists inside", "Zero inside", "Maximum inside", "Random inside"], a: 1 },
{ q: "Gauss’s law is based on", o: ["Conservation of energy", "Conservation of charge", "Newton’s law", "Coulomb’s law only"], a: 1 },
{ q: "Field lines are closer where field is", o: ["Weak", "Strong", "Zero", "Uniform"], a: 1 },
{ q: "Electric field inside hollow conductor is zero due to", o: ["Symmetry", "Redistribution of charges", "Gauss’s law", "All of these"], a: 3 }
];
