const questions = [
{ q: "Electrostatic potential at a point is defined as", o: ["Work done per unit charge", "Force per unit charge", "Energy per unit mass", "Charge per unit work"], a: 0 },
{ q: "SI unit of electric potential is", o: ["Joule", "Coulomb", "Volt", "Newton"], a: 2 },
{ q: "One volt is equal to", o: ["1 J/C", "1 C/J", "1 N/C", "1 N·m"], a: 0 },
{ q: "Electric potential is a", o: ["Vector quantity", "Scalar quantity", "Tensor quantity", "Dimensionless quantity"], a: 1 },
{ q: "Electric potential due to a point charge varies as", o: ["1/r", "1/r²", "r", "r²"], a: 0 },
{ q: "Electric potential at infinity is taken as", o: ["Maximum", "Zero", "Infinite", "Minimum"], a: 1 },
{ q: "Potential due to a positive charge is", o: ["Always negative", "Always positive", "Zero", "Depends on distance only"], a: 1 },
{ q: "Electric potential energy of two point charges depends on", o: ["Charge only", "Distance only", "Charges and distance", "Mass"], a: 2 },
{ q: "Work done in moving a charge along an equipotential surface is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "Electric field is perpendicular to", o: ["Magnetic field", "Equipotential surface", "Direction of force", "Charge"], a: 1 },
{ q: "Equipotential surfaces can", o: ["Intersect", "Be parallel always", "Never intersect", "Be curved only"], a: 2 },
{ q: "Equipotential surfaces are closer where electric field is", o: ["Weak", "Strong", "Zero", "Uniform"], a: 1 },
{ q: "Potential inside a charged conductor is", o: ["Zero", "Maximum", "Constant", "Infinite"], a: 2 },
{ q: "Electric potential inside a hollow conductor is", o: ["Zero", "Constant", "Infinite", "Variable"], a: 1 },
{ q: "Relation between electric field and potential is", o: ["E = –dV/dr", "E = dV/dr", "V = –dE/dr", "E = V/r"], a: 0 },
{ q: "Potential difference between two points is", o: ["Scalar", "Vector", "Zero always", "Direction dependent"], a: 0 },
{ q: "Electric potential due to an electric dipole at its centre is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "Potential due to an electric dipole on equatorial line is", o: ["Zero", "Maximum", "Infinite", "Negative"], a: 0 },
{ q: "Potential due to dipole on axial line is", o: ["Zero", "Depends on distance", "Constant", "Infinite"], a: 1 },
{ q: "Capacitance is defined as", o: ["Charge × potential", "Charge / potential", "Potential / charge", "Energy / charge"], a: 1 },
{ q: "SI unit of capacitance is", o: ["Coulomb", "Volt", "Farad", "Joule"], a: 2 },
{ q: "Capacitance depends on", o: ["Charge", "Potential", "Geometry of conductor", "Current"], a: 2 },
{ q: "Capacitance of an isolated conductor depends on", o: ["Shape and size", "Charge only", "Potential only", "Material only"], a: 0 },
{ q: "Capacitance of a parallel plate capacitor is", o: ["ε₀A/d", "ε₀d/A", "A/ε₀d", "ε₀/d"], a: 0 },
{ q: "If distance between plates is doubled, capacitance becomes", o: ["Double", "Half", "Four times", "Same"], a: 1 },
{ q: "Inserting dielectric between plates increases", o: ["Electric field", "Capacitance", "Potential difference", "Charge leakage"], a: 1 },
{ q: "Dielectric constant (K) is equal to", o: ["ε₀", "ε/ε₀", "ε₀/ε", "1/ε"], a: 1 },
{ q: "Unit of dielectric constant is", o: ["Farad", "Volt", "Dimensionless", "C/m²"], a: 2 },
{ q: "Electric field inside dielectric reduces by factor", o: ["K", "1/K", "K²", "√K"], a: 1 },
{ q: "Capacitance of capacitor filled with dielectric is", o: ["C/K", "KC", "C/K²", "Same"], a: 1 },
{ q: "Energy stored in a capacitor is", o: ["CV²", "½CV²", "QV", "Q²C"], a: 1 },
{ q: "Energy density of electric field is", o: ["½ε₀E²", "ε₀E", "E²/ε₀", "ε₀/E²"], a: 0 },
{ q: "Capacitors in series have", o: ["Same charge", "Same potential", "Same energy", "Same capacitance"], a: 0 },
{ q: "Equivalent capacitance in series is", o: ["Greater than smallest", "Less than smallest", "Equal to largest", "Sum of capacitances"], a: 1 },
{ q: "Capacitors in parallel have", o: ["Same charge", "Same potential difference", "Same energy", "Zero charge"], a: 1 },
{ q: "Equivalent capacitance in parallel is", o: ["Less than smallest", "Equal to smallest", "Greater than largest", "Zero"], a: 2 },
{ q: "Work done in charging a capacitor is stored as", o: ["Heat", "Kinetic energy", "Electric potential energy", "Magnetic energy"], a: 2 },
{ q: "Energy stored in capacitor depends on", o: ["Charge", "Voltage", "Capacitance", "All of these"], a: 3 },
{ q: "If potential is constant, increasing capacitance will", o: ["Increase energy", "Decrease energy", "Not affect energy", "Make energy zero"], a: 0 },
{ q: "If charge is constant, increasing capacitance will", o: ["Increase energy", "Decrease energy", "Not change energy", "Double energy"], a: 1 },
{ q: "Capacitance of spherical conductor of radius R is", o: ["4πɛ₀R", "ɛ₀R", "R/4πɛ₀", "πɛ₀R"], a: 0 },
{ q: "Potential of a charged spherical conductor is", o: ["Same everywhere inside", "Zero at surface", "Maximum at centre", "Different inside"], a: 0 },
{ q: "Equipotential surface around a point charge is", o: ["Plane", "Cylinder", "Sphere", "Cone"], a: 2 },
{ q: "Electric field is zero where potential is", o: ["Maximum", "Minimum", "Constant", "Zero"], a: 2 },
{ q: "Potential gradient gives", o: ["Force", "Electric field", "Energy", "Charge"], a: 1 },
{ q: "A capacitor is fully charged when", o: ["Current is maximum", "Voltage is zero", "Current is zero", "Energy is zero"], a: 2 },
{ q: "A farad is a very", o: ["Small unit", "Large unit", "Medium unit", "Practical unit"], a: 1 },
{ q: "Energy loss during charging of capacitor is due to", o: ["Dielectric", "Resistance", "Capacitance", "Electric field"], a: 1 },
{ q: "Electric potential is path independent because field is", o: ["Uniform", "Conservative", "Central", "Weak"], a: 1 },
{ q: "Potential due to a ring at its centre is", o: ["Zero", "Maximum", "Infinite", "Depends on charge"], a: 1 },
{ q: "Electric potential due to infinite plane sheet is", o: ["Zero", "Constant", "Infinite", "Variable"], a: 2 },
{ q: "In presence of dielectric, potential difference between plates", o: ["Increases", "Decreases", "Remains same", "Becomes zero"], a: 1 },
{ q: "Polarization in dielectric causes", o: ["Increase in field", "Decrease in field", "No change", "Infinite field"], a: 1 },
{ q: "Dielectrics are", o: ["Good conductors", "Insulators", "Semiconductors", "Superconductors"], a: 1 },
{ q: "Electric potential energy is maximum when dipole is", o: ["Parallel to field", "Perpendicular to field", "Anti-parallel to field", "Zero field"], a: 2 },
{ q: "For a charged conductor, potential is", o: ["Zero everywhere", "Same throughout", "Maximum at surface", "Minimum at centre"], a: 1 },
{ q: "Capacity of Earth is approximately", o: ["7.1 × 10⁻⁴ F", "7.1 × 10⁻¹ F", "7.1 × 10² F", "7.1 F"], a: 0 },
{ q: "Capacitor used for storing large energy should have", o: ["Low voltage", "High capacitance", "Small area", "Large separation"], a: 1 },
{ q: "Two capacitors C and 2C in series have equivalent capacitance", o: ["C", "2C", "2C/3", "3C"], a: 2 },
{ q: "Two capacitors C and 2C in parallel have equivalent capacitance", o: ["C", "2C", "3C", "C/2"], a: 2 },
{ q: "Energy stored per unit volume is called", o: ["Electric potential", "Energy density", "Capacitance", "Flux"], a: 1 },
{ q: "Potential difference across a capacitor is zero when", o: ["Fully charged", "Discharged", "Dielectric inserted", "Resistance present"], a: 1 },
{ q: "A capacitor blocks", o: ["DC", "AC", "Both", "None"], a: 0 },
{ q: "Capacitors are used in", o: ["Filters", "Tuning circuits", "Energy storage", "All of these"], a: 3 },
{ q: "Electric potential decreases in direction of", o: ["Electric field", "Opposite to field", "Perpendicular to field", "Random"], a: 0 },
{ q: "Relation between V and E is", o: ["V = ∫E·dr", "V = –∫E·dr", "E = ∫V·dr", "E = V·r"], a: 1 },
{ q: "Capacitance does NOT depend on", o: ["Area", "Distance", "Dielectric", "Charge"], a: 3 },
{ q: "Potential difference between plates increases when", o: ["Dielectric inserted (isolated)", "Dielectric removed", "Area increased", "Distance decreased"], a: 1 },
{ q: "Energy stored in capacitor is minimum when", o: ["Fully charged", "Partially charged", "Discharged", "Dielectric present"], a: 2 },
{ q: "Equipotential surfaces are useful to", o: ["Store charge", "Find direction of field", "Increase capacitance", "Measure current"], a: 1 }
];
