const questions = [
{ q: "Electric current is defined as", o: ["Charge × time", "Charge / time", "Time / charge", "Energy / charge"], a: 1 },
{ q: "SI unit of electric current is", o: ["Volt", "Ampere", "Ohm", "Coulomb"], a: 1 },
{ q: "1 ampere is equal to", o: ["1 J/s", "1 C/s", "1 N/C", "1 V/C"], a: 1 },
{ q: "Conventional current flows from", o: ["Negative to positive", "Positive to negative", "Both directions", "Randomly"], a: 1 },
{ q: "Drift velocity of electrons is", o: ["Very large", "Equal to speed of light", "Very small", "Zero"], a: 2 },
{ q: "Ohm’s law is valid when", o: ["Temperature changes", "Physical conditions remain constant", "Current is high", "Voltage is zero"], a: 1 },
{ q: "Ohm’s law is", o: ["V = IR", "I = VR", "R = VI", "V = R/I"], a: 0 },
{ q: "Resistance is measured in", o: ["Ampere", "Volt", "Ohm", "Watt"], a: 2 },
{ q: "Resistance of a conductor depends on", o: ["Length", "Area", "Material", "All of these"], a: 3 },
{ q: "Resistance increases with increase in", o: ["Area", "Length", "Temperature (for metals)", "Diameter"], a: 2 },
{ q: "Resistivity depends on", o: ["Length", "Area", "Shape", "Material and temperature"], a: 3 },
{ q: "SI unit of resistivity is", o: ["Ω", "Ω m", "Ω/m", "m/Ω"], a: 1 },
{ q: "Resistance of a wire is doubled when", o: ["Length is doubled", "Area is doubled", "Radius is doubled", "Temperature is halved"], a: 0 },
{ q: "Temperature coefficient of resistance for metals is", o: ["Negative", "Zero", "Positive", "Infinite"], a: 2 },
{ q: "Which material has negative temperature coefficient?", o: ["Copper", "Iron", "Carbon", "Aluminium"], a: 2 },
{ q: "Superconductors have resistance", o: ["Very high", "Very low", "Zero", "Infinite"], a: 2 },
{ q: "Equivalent resistance in series is", o: ["Less than smallest", "Greater than largest", "Equal to smallest", "Zero"], a: 1 },
{ q: "Equivalent resistance in parallel is", o: ["Greater than largest", "Less than smallest", "Equal to sum", "Infinite"], a: 1 },
{ q: "In series combination, current is", o: ["Different in each resistor", "Same in all resistors", "Zero", "Maximum"], a: 1 },
{ q: "In parallel combination, voltage across each resistor is", o: ["Different", "Zero", "Same", "Infinite"], a: 2 },
{ q: "Electric power is given by", o: ["P = IV", "P = I²R", "P = V²/R", "All of these"], a: 3 },
{ q: "SI unit of electric power is", o: ["Joule", "Watt", "Volt", "Ampere"], a: 1 },
{ q: "Electrical energy is measured in", o: ["Watt", "Joule", "kWh", "Both B and C"], a: 3 },
{ q: "Heating effect of current is based on", o: ["Ohm’s law", "Joule’s law", "Kirchhoff’s law", "Faraday’s law"], a: 1 },
{ q: "Heat produced in a resistor is proportional to", o: ["I", "I²", "V", "R"], a: 1 },
{ q: "EMF of a cell is defined as", o: ["Potential difference in open circuit", "Work per unit charge", "Terminal voltage", "Current × resistance"], a: 1 },
{ q: "EMF is measured in", o: ["Ampere", "Ohm", "Volt", "Watt"], a: 2 },
{ q: "Internal resistance of a cell depends on", o: ["Area of electrodes", "Distance between electrodes", "Nature of electrolyte", "All of these"], a: 3 },
{ q: "Terminal voltage of a cell is less than EMF when", o: ["Cell is open", "No current flows", "Current is drawn", "Internal resistance is zero"], a: 2 },
{ q: "Kirchhoff’s first law is based on", o: ["Conservation of charge", "Conservation of energy", "Ohm’s law", "Joule’s law"], a: 0 },
{ q: "Kirchhoff’s second law is based on", o: ["Charge conservation", "Energy conservation", "Momentum conservation", "Mass conservation"], a: 1 },
{ q: "Wheatstone bridge is used to measure", o: ["Voltage", "Current", "Resistance", "Power"], a: 2 },
{ q: "Wheatstone bridge is balanced when", o: ["P/Q = R/S", "P+Q = R+S", "PQ = RS", "P = Q = R = S"], a: 0 },
{ q: "Meter bridge works on principle of", o: ["Ohm’s law", "Kirchhoff’s law", "Wheatstone bridge", "Joule’s law"], a: 2 },
{ q: "Galvanometer is used to detect", o: ["Voltage", "Resistance", "Current", "Power"], a: 2 },
{ q: "A galvanometer can be converted into an ammeter by connecting", o: ["High resistance in series", "Low resistance in parallel", "High resistance in parallel", "Low resistance in series"], a: 1 },
{ q: "Ammeter is connected in", o: ["Parallel", "Series", "Any way", "Diagonal"], a: 1 },
{ q: "Voltmeter is connected in", o: ["Series", "Parallel", "Any way", "Diagonal"], a: 1 },
{ q: "Voltmeter has", o: ["Low resistance", "Zero resistance", "High resistance", "Infinite current"], a: 2 },
{ q: "Potentiometer is used to measure", o: ["Current", "Resistance", "EMF accurately", "Power"], a: 2 },
{ q: "Advantage of potentiometer over voltmeter is", o: ["Portable", "No power consumption", "High sensitivity", "Cheap"], a: 2 },
{ q: "In potentiometer, balancing length is proportional to", o: ["Current", "Resistance", "EMF", "Power"], a: 2 },
{ q: "Drift velocity is proportional to", o: ["Electric field", "Resistance", "Area", "Length"], a: 0 },
{ q: "Current density is given by", o: ["I/A", "I × A", "V/R", "Q/t"], a: 0 },
{ q: "Relation between current density and drift velocity is", o: ["J = nqv", "J = q/nv", "J = v/nq", "J = nq/v"], a: 0 },
{ q: "Copper is preferred for electrical wiring because", o: ["Cheap", "High resistivity", "Low resistivity", "High temperature coefficient"], a: 2 },
{ q: "Nichrome is used in heating elements due to", o: ["Low melting point", "High resistivity", "Low resistivity", "Superconductivity"], a: 1 },
{ q: "Fuse wire is made of material with", o: ["High melting point", "Low melting point", "High conductivity", "Zero resistance"], a: 1 },
{ q: "If resistance of a wire is R, then resistance of same wire cut into two equal parts is", o: ["R", "R/2", "2R", "R/4"], a: 1 },
{ q: "Electric current in metals is due to flow of", o: ["Protons", "Ions", "Electrons", "Holes"], a: 2 }
];
