const questions = [
{ q: "Magnetic force on a moving charge is maximum when velocity is", o: ["Parallel to magnetic field", "Perpendicular to magnetic field", "Anti-parallel to magnetic field", "Zero"], a: 1 },
{ q: "Magnetic force on a stationary charge is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 2 },
{ q: "SI unit of magnetic field is", o: ["Weber", "Tesla", "Ampere", "Henry"], a: 1 },
{ q: "Magnetic force on charge q moving with velocity v in field B is", o: ["qvB", "qvB sinθ", "qvB cosθ", "qB/v"], a: 1 },
{ q: "Direction of magnetic force is given by", o: ["Fleming’s left-hand rule", "Fleming’s right-hand rule", "Right-hand thumb rule", "Maxwell’s rule"], a: 0 },
{ q: "Magnetic force does no work because it is always", o: ["Zero", "Parallel to velocity", "Perpendicular to velocity", "Opposite to velocity"], a: 2 },
{ q: "Path of charged particle moving perpendicular to uniform magnetic field is", o: ["Straight line", "Parabolic", "Circular", "Elliptical"], a: 2 },
{ q: "Radius of circular path of charged particle is proportional to", o: ["Charge", "Magnetic field", "Velocity", "1/mass"], a: 2 },
{ q: "Time period of charged particle in magnetic field depends on", o: ["Velocity", "Radius", "Magnetic field and mass", "Charge and mass"], a: 3 },
{ q: "Cyclotron works on principle that", o: ["Electric field is uniform", "Frequency is constant", "Magnetic field varies", "Energy increases linearly"], a: 1 },
{ q: "Cyclotron cannot accelerate", o: ["Protons", "Deuterons", "Alpha particles", "Electrons"], a: 3 },
{ q: "SI unit of magnetic flux is", o: ["Tesla", "Weber", "Henry", "Ampere"], a: 1 },
{ q: "Biot–Savart law gives magnetic field due to", o: ["Moving charge", "Stationary charge", "Current element", "Magnetic pole"], a: 2 },
{ q: "Magnetic field at centre of circular current-carrying loop is proportional to", o: ["Radius", "Square of current", "Current", "1/current"], a: 2 },
{ q: "Magnetic field at centre of a circular coil increases when", o: ["Radius increases", "Current decreases", "Number of turns increases", "Coil is removed"], a: 2 },
{ q: "Magnetic field due to long straight current-carrying conductor varies as", o: ["r", "r²", "1/r", "1/r²"], a: 2 },
{ q: "Direction of magnetic field around straight conductor is given by", o: ["Fleming’s left-hand rule", "Fleming’s right-hand rule", "Right-hand thumb rule", "Maxwell’s rule"], a: 2 },
{ q: "Ampere’s circuital law is applicable for", o: ["Electrostatic field", "Uniform magnetic field", "Symmetric current distribution", "All magnetic fields"], a: 2 },
{ q: "Force on a current-carrying conductor is maximum when conductor is", o: ["Parallel to magnetic field", "Perpendicular to magnetic field", "At 45° to field", "At any angle"], a: 1 },
{ q: "SI unit of magnetic permeability is", o: ["T m/A", "H/m", "N/A²", "Wb/m²"], a: 1 },
{ q: "Force on a current-carrying conductor is given by", o: ["BIL", "BIL sinθ", "BIL cosθ", "BI/L"], a: 1 },
{ q: "Two parallel current-carrying conductors attract each other if currents are", o: ["Opposite", "Same direction", "Zero", "Unequal"], a: 1 },
{ q: "Two parallel conductors repel each other when currents flow in", o: ["Same direction", "Opposite direction", "Equal magnitude", "Zero"], a: 1 },
{ q: "Force per unit length between two parallel conductors defines", o: ["Volt", "Ohm", "Ampere", "Tesla"], a: 2 },
{ q: "Magnetic field inside long solenoid is", o: ["Zero", "Non-uniform", "Uniform", "Infinite"], a: 2 },
{ q: "Magnetic field inside solenoid depends on", o: ["Current", "Number of turns per unit length", "Permeability", "All of these"], a: 3 },
{ q: "Magnetic field inside toroid is", o: ["Uniform", "Zero", "Non-uniform", "Infinite"], a: 0 },
{ q: "Torque on a current loop in magnetic field is maximum when plane of loop is", o: ["Parallel to field", "Perpendicular to field", "Inclined at 45°", "Random"], a: 0 },
{ q: "Torque on current loop depends on", o: ["Current", "Area", "Magnetic field", "All of these"], a: 3 },
{ q: "Magnetic dipole moment of a current loop is", o: ["IA", "I/A", "A/I", "BIA"], a: 0 },
{ q: "SI unit of magnetic dipole moment is", o: ["A·m²", "T·m", "Wb/m", "N·m"], a: 0 },
{ q: "Potential energy of magnetic dipole is minimum when", o: ["Perpendicular to field", "Parallel to field", "Anti-parallel to field", "Zero field"], a: 1 },
{ q: "Potential energy of dipole is maximum when", o: ["Parallel to field", "Perpendicular to field", "Anti-parallel to field", "Zero field"], a: 2 },
{ q: "Magnetic field lines form", o: ["Open curves", "Closed loops", "Straight lines", "Random curves"], a: 1 },
{ q: "Magnetic field at a point is tangent to", o: ["Magnetic flux", "Electric field", "Field lines", "Equipotential surface"], a: 2 },
{ q: "Magnetic field lines are crowded where field is", o: ["Weak", "Uniform", "Strong", "Zero"], a: 2 },
{ q: "Magnetic field inside a hollow current-carrying conductor is", o: ["Zero", "Maximum", "Uniform", "Infinite"], a: 0 },
{ q: "Cyclotron frequency depends on", o: ["Velocity", "Radius", "Magnetic field and charge-to-mass ratio", "Energy"], a: 2 },
{ q: "Motion of charged particle in combined E and B fields (perpendicular) is", o: ["Circular", "Straight line", "Helical", "Parabolic"], a: 1 },
{ q: "Magnetic force acts as", o: ["Centripetal force", "Gravitational force", "Electric force", "Frictional force"], a: 0 },
{ q: "If velocity is parallel to magnetic field, path is", o: ["Circular", "Helical", "Straight line", "Parabolic"], a: 2 },
{ q: "Magnetic field at centre of semicircular arc is proportional to", o: ["Radius", "1/radius", "Radius²", "Independent of radius"], a: 1 },
{ q: "Fleming’s left-hand rule is used in", o: ["Generator", "Motor", "Transformer", "Battery"], a: 1 },
{ q: "Unit of magnetic field strength H is", o: ["Tesla", "A/m", "Wb", "Henry"], a: 1 },
{ q: "Earth’s magnetic field is approximately", o: ["10⁻⁶ T", "10⁻⁵ T", "10⁻⁴ T", "1 T"], a: 1 },
{ q: "Magnetic field due to moving charge depends on", o: ["Speed", "Direction of motion", "Charge", "All of these"], a: 3 },
{ q: "If magnetic field is doubled, radius of circular path becomes", o: ["Double", "Half", "Four times", "Same"], a: 1 },
{ q: "Charged particle moving at angle θ to B follows", o: ["Circular path", "Straight path", "Helical path", "Parabolic path"], a: 2 },
{ q: "SI unit of magnetic flux density is", o: ["Weber", "Tesla", "Henry", "Ampere"], a: 1 },
{ q: "Magnetic field inside solenoid is independent of", o: ["Current", "Number of turns", "Length", "Radius"], a: 3 }
];
