const questions = [
{ q: "A magnetic dipole consists of", o: ["Two electric charges", "Two magnetic poles of equal strength and opposite nature", "Two electric currents", "One north pole only"], a: 1 },
{ q: "Magnetic dipole moment of a bar magnet is", o: ["m × l", "m / l", "l / m", "m + l"], a: 0 },
{ q: "SI unit of magnetic dipole moment is", o: ["Tesla", "Weber", "A·m²", "N·m"], a: 2 },
{ q: "Magnetic field on axial line of a bar magnet is proportional to", o: ["1/r", "1/r²", "1/r³", "r³"], a: 2 },
{ q: "Magnetic field on equatorial line of a bar magnet is proportional to", o: ["1/r", "1/r²", "1/r³", "r"], a: 2 },
{ q: "Ratio of magnetic field on axial line to equatorial line at same distance is", o: ["1 : 1", "2 : 1", "1 : 2", "4 : 1"], a: 1 },
{ q: "Direction of magnetic field on equatorial line is", o: ["Same as dipole moment", "Opposite to dipole moment", "Perpendicular to dipole moment", "Zero"], a: 1 },
{ q: "Torque acting on a magnetic dipole in uniform magnetic field is", o: ["MB", "MB sinθ", "MB cosθ", "M/B"], a: 1 },
{ q: "Torque on magnetic dipole is maximum when angle between M and B is", o: ["0°", "30°", "90°", "180°"], a: 2 },
{ q: "Potential energy of magnetic dipole is minimum when it is", o: ["Perpendicular to field", "Parallel to field", "Anti-parallel to field", "At any angle"], a: 1 },
{ q: "Potential energy of magnetic dipole is maximum when", o: ["Parallel to field", "Perpendicular to field", "Anti-parallel to field", "Zero field"], a: 2 },
{ q: "Magnetic field lines of bar magnet", o: ["Start from north pole and end at south pole", "Form closed loops", "Are straight lines", "Never intersect"], a: 1 },
{ q: "Magnetic field inside a bar magnet is directed from", o: ["North to South", "South to North", "East to West", "West to East"], a: 1 },
{ q: "Magnetic susceptibility (χ) is defined as", o: ["M/B", "B/H", "H/B", "μ₀χ"], a: 0 },
{ q: "Magnetic permeability (μ) is given by", o: ["B/H", "H/B", "M/H", "χ/H"], a: 0 },
{ q: "Relation between μ and χ is", o: ["μ = μ₀χ", "μ = μ₀(1 + χ)", "μ = χ/μ₀", "μ = 1 + χ"], a: 1 },
{ q: "Diamagnetic substances have susceptibility", o: ["Positive and small", "Negative and small", "Positive and large", "Zero"], a: 1 },
{ q: "Paramagnetic substances have susceptibility", o: ["Negative", "Zero", "Positive and small", "Positive and large"], a: 2 },
{ q: "Ferromagnetic substances have susceptibility", o: ["Negative", "Small positive", "Large positive", "Zero"], a: 2 },
{ q: "Which of the following is diamagnetic?", o: ["Iron", "Aluminium", "Copper", "Nickel"], a: 2 },
{ q: "Which of the following is paramagnetic?", o: ["Bismuth", "Copper", "Aluminium", "Mercury"], a: 2 },
{ q: "Which of the following is ferromagnetic?", o: ["Aluminium", "Copper", "Iron", "Bismuth"], a: 2 },
{ q: "Curie’s law is applicable to", o: ["Diamagnetic substances", "Paramagnetic substances", "Ferromagnetic substances", "Superconductors"], a: 1 },
{ q: "According to Curie’s law, susceptibility is proportional to", o: ["Temperature", "1/Temperature", "Temperature²", "Constant"], a: 1 },
{ q: "Curie temperature is the temperature above which", o: ["Paramagnetic becomes diamagnetic", "Ferromagnetic becomes paramagnetic", "Diamagnetic becomes paramagnetic", "Magnetism disappears"], a: 1 },
{ q: "Retentivity is the property of a magnetic material to", o: ["Resist magnetisation", "Retain magnetisation", "Lose magnetisation quickly", "Conduct electricity"], a: 1 },
{ q: "Coercivity is the measure of", o: ["Ability to retain magnetism", "Ability to resist demagnetisation", "Magnetic field strength", "Susceptibility"], a: 1 },
{ q: "Material used for permanent magnets should have", o: ["Low retentivity and low coercivity", "High retentivity and low coercivity", "High retentivity and high coercivity", "Low retentivity and high coercivity"], a: 2 },
{ q: "Soft iron is used for electromagnets because it has", o: ["High retentivity", "Low retentivity", "High coercivity", "High resistance"], a: 1 },
{ q: "Hysteresis loop is plotted between", o: ["B and H", "M and B", "χ and H", "μ and H"], a: 0 },
{ q: "Area of hysteresis loop represents", o: ["Energy stored", "Energy lost per cycle", "Magnetic field strength", "Susceptibility"], a: 1 },
{ q: "SI unit of magnetic field strength (H) is", o: ["Tesla", "Weber", "Ampere per metre", "Henry"], a: 2 },
{ q: "Earth’s magnetic field resembles that of", o: ["Straight wire", "Circular coil", "Bar magnet", "Solenoid"], a: 2 },
{ q: "Magnetic declination is the angle between", o: ["Geographic and magnetic meridian", "Magnetic and horizontal plane", "Magnetic field and equator", "Geographic and equator"], a: 0 },
{ q: "Magnetic dip is the angle between", o: ["Magnetic field and horizontal plane", "Magnetic field and vertical plane", "Geographic meridian and equator", "Magnetic and geographic meridian"], a: 0 },
{ q: "Angle of dip at magnetic equator is", o: ["0°", "30°", "45°", "90°"], a: 0 },
{ q: "Angle of dip at magnetic poles is", o: ["0°", "45°", "60°", "90°"], a: 3 },
{ q: "Horizontal component of Earth’s magnetic field is zero at", o: ["Magnetic equator", "Magnetic poles", "Geographic equator", "Tropics"], a: 1 },
{ q: "Vertical component of Earth’s magnetic field is zero at", o: ["Magnetic equator", "Magnetic poles", "North pole", "South pole"], a: 0 },
{ q: "Magnetic moment of Earth is directed from", o: ["Geographic north to south", "Magnetic south to magnetic north", "Geographic south to north", "East to west"], a: 1 },
{ q: "Magnetic intensity is also called", o: ["Magnetic flux", "Magnetising field", "Magnetic induction", "Susceptibility"], a: 1 },
{ q: "Diamagnetic substances are weakly", o: ["Attracted by magnetic field", "Repelled by magnetic field", "Magnetised permanently", "Neutral"], a: 1 },
{ q: "Paramagnetic substances are", o: ["Strongly magnetised", "Weakly attracted", "Strongly repelled", "Superconducting"], a: 1 },
{ q: "Ferromagnetic substances lose magnetism above", o: ["Absolute zero", "Room temperature", "Curie temperature", "Boiling point"], a: 2 },
{ q: "Example of diamagnetic material is", o: ["Aluminium", "Copper", "Iron", "Cobalt"], a: 1 },
{ q: "Example of paramagnetic material is", o: ["Bismuth", "Copper", "Aluminium", "Mercury"], a: 2 },
{ q: "Example of ferromagnetic material is", o: ["Nickel", "Zinc", "Copper", "Silver"], a: 0 },
{ q: "Magnetic field inside a magnet is", o: ["Zero", "Uniform", "Non-uniform", "Infinite"], a: 2 },
{ q: "SI unit of magnetisation (M) is", o: ["Tesla", "Weber", "A/m", "N·m"], a: 2 },
{ q: "Magnetic susceptibility of vacuum is", o: ["Zero", "One", "Negative", "Infinite"], a: 0 }
];
