const questions = [
{ q: "The instantaneous current in an AC circuit is given by", o: ["I = I₀", "I = I₀ sin(ωt)", "I = I₀ t", "I = 0"], a: 1 },
{ q: "RMS value of AC is related to peak value by", o: ["Irms = I₀", "Irms = I₀/√2", "Irms = √2 I₀", "Irms = I₀/2"], a: 1 },
{ q: "Average value of sinusoidal AC over one complete cycle is", o: ["I₀", "I₀/√2", "Zero", "I₀/2"], a: 2 },
{ q: "Peak value of current in AC is", o: ["I₀/√2", "I₀", "√2 I₀", "Zero"], a: 1 },
{ q: "Reactance of a pure inductor is", o: ["R", "1/ωL", "ωL", "0"], a: 2 },
{ q: "Reactance of a pure capacitor is", o: ["R", "1/ωC", "ωC", "0"], a: 1 },
{ q: "Impedance in series LCR circuit is given by", o: ["Z = R + XL + XC", "Z = √(R² + (XL − XC)²)", "Z = √(R² + XL² + XC²)", "Z = R/X"], a: 1 },
{ q: "In pure resistor, voltage and current are", o: ["In phase", "90° out of phase", "180° out of phase", "Zero phase difference"], a: 0 },
{ q: "In pure inductor, current lags voltage by", o: ["0°", "90°", "180°", "45°"], a: 1 },
{ q: "In pure capacitor, current leads voltage by", o: ["0°", "90°", "180°", "45°"], a: 1 },
{ q: "Resonance occurs in LCR series circuit when", o: ["XL = 0", "XC = 0", "XL = XC", "R = 0"], a: 2 },
{ q: "Resonant frequency of series LCR circuit is", o: ["1/(2πRC)", "1/(2π√(LC))", "R/L", "L/C"], a: 1 },
{ q: "Quality factor Q is given by", o: ["Q = XL/R", "Q = R/XL", "Q = ω₀L/R", "Q = 1/R"], a: 2 },
{ q: "Average power in AC circuit is", o: ["Zero", "V₀I₀", "P = Vrms Irms cosφ", "V₀I₀ cos²φ"], a: 2 },
{ q: "Power factor is", o: ["cosφ", "sinφ", "tanφ", "1"], a: 0 },
{ q: "Maximum current in series LCR circuit at resonance is", o: ["I₀ = V/Z", "I₀ = V/R", "I₀ = V/(XL + XC)", "Zero"], a: 1 },
{ q: "In series LCR at resonance, impedance is", o: ["Zero", "R", "XL + XC", "Infinite"], a: 1 },
{ q: "In parallel resonance circuit, current is", o: ["Maximum", "Minimum", "Zero", "Infinite"], a: 1 },
{ q: "In AC, energy is stored in", o: ["Resistor only", "Inductor and capacitor", "Capacitor only", "Inductor only"], a: 1 },
{ q: "In pure AC, net energy transferred to inductor over one cycle is", o: ["Maximum", "Zero", "Half", "Infinite"], a: 1 },
{ q: "In pure AC, net energy transferred to capacitor over one cycle is", o: ["Maximum", "Zero", "Half", "Infinite"], a: 1 },
{ q: "RMS voltage of sinusoidal AC is related to peak voltage by", o: ["V₀/2", "V₀/√2", "√2 V₀", "V₀"], a: 1 },
{ q: "In LCR series, phase angle φ is", o: ["tanφ = (XL + XC)/R", "tanφ = (XL − XC)/R", "tanφ = R/(XL − XC)", "Zero"], a: 1 },
{ q: "In series LCR at resonance, phase angle φ is", o: ["0°", "90°", "180°", "45°"], a: 0 },
{ q: "Maximum voltage across inductor at resonance is", o: ["V = I₀R", "V = I₀XL", "V = I₀XC", "Zero"], a: 1 },
{ q: "Maximum voltage across capacitor at resonance is", o: ["V = I₀R", "V = I₀XL", "V = I₀XC", "Zero"], a: 2 },
{ q: "In AC, instantaneous power is", o: ["VI", "VI cosφ", "VI sinφ", "½VI"], a: 0 },
{ q: "Average power is maximum when", o: ["φ = 0°", "φ = 90°", "φ = 180°", "φ = 45°"], a: 0 },
{ q: "Inductive reactance increases with", o: ["Frequency", "Resistance", "Capacitance", "Voltage"], a: 0 },
{ q: "Capacitive reactance decreases with", o: ["Frequency", "Resistance", "Capacitance", "Voltage"], a: 0 },
{ q: "In pure resistive AC, power factor is", o: ["0", "1", "0.5", "2"], a: 1 },
{ q: "In pure inductive AC, power factor is", o: ["0", "1", "0.5", "√2"], a: 0 },
{ q: "In pure capacitive AC, power factor is", o: ["0", "1", "0.5", "√2"], a: 0 },
{ q: "Inductive and capacitive reactances are equal at", o: ["Resonance", "Zero frequency", "Infinite frequency", "Maximum frequency"], a: 0 },
{ q: "In LCR series, current is minimum at", o: ["Resonance", "Zero frequency", "Very high frequency", "None"], a: 1 },
{ q: "In series AC, voltage leads current across", o: ["Resistor", "Inductor", "Capacitor", "None"], a: 1 },
{ q: "In series AC, voltage lags current across", o: ["Resistor", "Inductor", "Capacitor", "None"], a: 2 },
{ q: "Peak power in AC circuit is", o: ["V₀I₀/2", "V₀I₀", "V₀I₀cosφ", "V₀I₀sinφ"], a: 1 },
{ q: "Lissajous figure on CRO is used to measure", o: ["Frequency", "Phase difference", "Voltage", "Resistance"], a: 1 },
{ q: "Phase difference between voltage and current in pure resistor is", o: ["0°", "90°", "180°", "45°"], a: 0 },
{ q: "Phase difference between voltage and current in pure inductor is", o: ["0°", "90°", "180°", "45°"], a: 1 },
{ q: "Phase difference between voltage and current in pure capacitor is", o: ["0°", "90°", "180°", "45°"], a: 1 },
{ q: "Impedance in purely resistive AC is", o: ["Zero", "R", "XL", "XC"], a: 1 },
{ q: "Impedance in purely inductive AC is", o: ["R", "XL", "XC", "0"], a: 1 },
{ q: "Impedance in purely capacitive AC is", o: ["R", "XL", "XC", "0"], a: 2 },
{ q: "Unit of impedance is", o: ["Ohm", "Henry", "Tesla", "Volt"], a: 0 },
{ q: "In resonance, voltages across L and C are", o: ["Zero", "Maximum", "Minimum", "Equal and opposite"], a: 3 },
{ q: "Average power in pure reactance circuit is", o: ["Maximum", "Zero", "Half", "Infinite"], a: 1 },
{ q: "In series LCR circuit, maximum current occurs at", o: ["XL > XC", "XL < XC", "XL = XC", "R = 0"], a: 2 },
{ q: "Energy oscillates between", o: ["Resistor and inductor", "Inductor and capacitor", "Resistor and capacitor", "Resistor only"], a: 1 }
];
