const questions = [
{ q: "Electromagnetic induction was discovered by", o: ["Maxwell", "Faraday", "Ampere", "Oersted"], a: 1 },
{ q: "Faraday’s first law states that induced emf is produced when", o: ["Current flows", "Magnetic field changes", "Magnetic flux linked with a circuit changes", "Resistance changes"], a: 2 },
{ q: "Faraday’s second law gives the magnitude of", o: ["Current", "Flux", "Induced emf", "Resistance"], a: 2 },
{ q: "SI unit of magnetic flux is", o: ["Tesla", "Weber", "Henry", "Volt"], a: 1 },
{ q: "SI unit of induced emf is", o: ["Ampere", "Volt", "Ohm", "Weber"], a: 1 },
{ q: "Lenz’s law is a consequence of", o: ["Conservation of charge", "Conservation of mass", "Conservation of energy", "Conservation of momentum"], a: 2 },
{ q: "Direction of induced current is given by", o: ["Fleming’s left-hand rule", "Fleming’s right-hand rule", "Lenz’s law", "Maxwell’s rule"], a: 2 },
{ q: "Negative sign in Faraday’s law indicates", o: ["Increase in flux", "Decrease in flux", "Direction of induced emf", "Magnitude of emf"], a: 2 },
{ q: "Induced emf depends on rate of change of", o: ["Current", "Electric field", "Magnetic flux", "Resistance"], a: 2 },
{ q: "Induced emf in a coil of N turns is", o: ["N(dΦ/dt)", "d(NΦ)/dt", "–N(dΦ/dt)", "–d(NΦ)/dt"], a: 3 },
{ q: "Self-inductance of a coil depends on", o: ["Shape and size", "Number of turns", "Core material", "All of these"], a: 3 },
{ q: "SI unit of self-inductance is", o: ["Tesla", "Weber", "Henry", "Volt"], a: 2 },
{ q: "Self-inductance is the property of a coil to oppose change in", o: ["Voltage", "Current", "Resistance", "Power"], a: 1 },
{ q: "Mutual inductance exists between", o: ["Two charges", "Two resistors", "Two coils", "Two capacitors"], a: 2 },
{ q: "SI unit of mutual inductance is", o: ["Henry", "Tesla", "Weber", "Ampere"], a: 0 },
{ q: "Induced emf due to self-induction is", o: ["–L dI/dt", "L dI/dt", "–I dL/dt", "L I"], a: 0 },
{ q: "Energy stored in an inductor is", o: ["½LI²", "LI²", "½CV²", "CV²"], a: 0 },
{ q: "Unit of energy stored in inductor is", o: ["Henry", "Joule", "Volt", "Watt"], a: 1 },
{ q: "Mutual inductance depends on", o: ["Distance between coils", "Orientation of coils", "Medium between coils", "All of these"], a: 3 },
{ q: "Eddy currents are", o: ["Useful currents", "Circulating currents induced in bulk conductors", "Surface currents", "Direct currents"], a: 1 },
{ q: "Eddy currents cause", o: ["Heating", "Energy loss", "Damping", "All of these"], a: 3 },
{ q: "Eddy current loss can be reduced by", o: ["Using solid core", "Increasing conductivity", "Laminating the core", "Increasing thickness"], a: 2 },
{ q: "Induced current produces magnetic field that", o: ["Supports change in flux", "Opposes change in flux", "Increases current", "Reduces resistance"], a: 1 },
{ q: "AC generator works on principle of", o: ["Mutual induction", "Self-induction", "Electromagnetic induction", "Magnetic effect of current"], a: 2 },
{ q: "Slip rings are used in AC generator to", o: ["Convert AC to DC", "Maintain continuity of current", "Increase emf", "Reduce losses"], a: 1 },
{ q: "Direction of induced emf in generator is given by", o: ["Fleming’s left-hand rule", "Fleming’s right-hand rule", "Maxwell’s rule", "Lenz’s law"], a: 1 },
{ q: "Maximum induced emf in generator depends on", o: ["Speed of rotation", "Magnetic field strength", "Area of coil", "All of these"], a: 3 },
{ q: "Magnetic flux through a coil is maximum when plane of coil is", o: ["Parallel to field", "Perpendicular to field", "Inclined at 45°", "Any angle"], a: 1 },
{ q: "Magnetic flux through a coil is zero when plane of coil is", o: ["Parallel to field", "Perpendicular to field", "At 45°", "Horizontal"], a: 0 },
{ q: "Back emf is observed in", o: ["Capacitor", "Inductor", "Resistor", "Voltmeter"], a: 1 },
{ q: "Back emf opposes", o: ["Applied voltage", "Current change", "Power", "Resistance"], a: 1 },
{ q: "Mutual inductance between two coils is zero when", o: ["Coils are close", "Coils are parallel", "Coils are perpendicular", "Coils have same turns"], a: 2 },
{ q: "Induced emf is zero when", o: ["Flux changes uniformly", "Flux is constant", "Coil moves", "Magnetic field exists"], a: 1 },
{ q: "Lenz’s law ensures that induced current", o: ["Increases energy", "Conserves energy", "Destroys energy", "Is maximum"], a: 1 },
{ q: "Transformer works on principle of", o: ["Self-induction", "Mutual induction", "Electromagnetic force", "Joule heating"], a: 1 },
{ q: "Eddy current braking is used in", o: ["Electric motors", "Speedometers", "AC generators", "Transformers"], a: 1 },
{ q: "SI unit of rate of change of magnetic flux is", o: ["Weber", "Weber/second", "Tesla", "Henry"], a: 1 },
{ q: "Induced emf is directly proportional to", o: ["Flux", "Time", "Rate of change of flux", "Area only"], a: 2 },
{ q: "Self-inductance of a straight wire is", o: ["Very large", "Infinite", "Very small", "Zero"], a: 2 },
{ q: "Inductor resists change in", o: ["Voltage", "Current", "Power", "Resistance"], a: 1 },
{ q: "Energy stored in magnetic field is due to", o: ["Electric field", "Magnetic field", "Motion of charges", "Heat"], a: 1 },
{ q: "Eddy currents are undesirable in", o: ["Induction furnace", "Electric brakes", "Transformers", "Speedometers"], a: 2 },
{ q: "Laminated core reduces", o: ["Hysteresis loss", "Copper loss", "Eddy current loss", "Leakage flux"], a: 2 },
{ q: "Induced emf does not depend on", o: ["Rate of change of flux", "Number of turns", "Resistance of coil", "Magnetic field"], a: 2 },
{ q: "Direction of induced current can be found using", o: ["Fleming’s left-hand rule", "Fleming’s right-hand rule", "Maxwell’s rule", "Joule’s law"], a: 1 },
{ q: "In a solenoid, self-inductance increases with", o: ["Decrease in turns", "Decrease in length", "Increase in turns", "Decrease in area"], a: 2 },
{ q: "Back emf in motor helps to", o: ["Increase speed", "Control current", "Increase power", "Reduce efficiency"], a: 1 },
{ q: "Magnetic flux linked with coil is zero if", o: ["Coil rotates", "Field exists", "Area is zero", "Coil is stationary"], a: 2 },
{ q: "Mutual inductance is maximum when", o: ["Coils are perpendicular", "Coils are far apart", "Coils are coaxial and close", "Coils have different turns"], a: 2 },
{ q: "Unit of inductance Henry is equivalent to", o: ["V·s/A", "Wb·A", "Ω/s", "J/A"], a: 0 }
];

