const questions = [
{ q: "Electromagnetic waves were predicted by", o: ["Faraday", "Maxwell", "Hertz", "Einstein"], a: 1 },
{ q: "Electromagnetic waves are produced by", o: ["Stationary charges", "Uniformly moving charges", "Accelerated charges", "Neutrons"], a: 2 },
{ q: "Speed of electromagnetic waves in vacuum is", o: ["3 × 10⁶ m/s", "3 × 10⁷ m/s", "3 × 10⁸ m/s", "3 × 10⁹ m/s"], a: 2 },
{ q: "Electromagnetic waves are", o: ["Longitudinal", "Transverse", "Both", "Neither"], a: 1 },
{ q: "In EM waves, electric and magnetic fields are", o: ["Parallel", "Anti-parallel", "Mutually perpendicular", "In opposite directions"], a: 2 },
{ q: "Ratio of electric field to magnetic field in EM wave equals", o: ["μ₀", "ε₀", "c", "1/c"], a: 2 },
{ q: "EM waves can travel through", o: ["Only vacuum", "Only medium", "Both vacuum and medium", "Neither"], a: 2 },
{ q: "Which of the following has highest frequency?", o: ["Radio waves", "Infrared", "Visible light", "Gamma rays"], a: 3 },
{ q: "Which EM waves are used in radar?", o: ["Radio waves", "Microwaves", "Infrared", "X-rays"], a: 1 },
{ q: "Which EM waves are used for sterilization?", o: ["Infrared", "Visible", "Ultraviolet", "Microwaves"], a: 2 },

{ q: "Which EM waves have the shortest wavelength?", o: ["X-rays", "Ultraviolet", "Gamma rays", "Microwaves"], a: 2 },
{ q: "Which EM waves are used in TV remote control?", o: ["Radio waves", "Infrared", "Microwaves", "X-rays"], a: 1 },
{ q: "Which EM waves cause sunburn?", o: ["Infrared", "Visible", "Ultraviolet", "Gamma rays"], a: 2 },
{ q: "Which EM waves are used in night vision devices?", o: ["Radio waves", "Infrared", "Ultraviolet", "X-rays"], a: 1 },
{ q: "Which EM waves are used for medical imaging of bones?", o: ["Infrared", "Ultraviolet", "X-rays", "Gamma rays"], a: 2 },
{ q: "Which EM waves have maximum penetrating power?", o: ["X-rays", "Ultraviolet", "Gamma rays", "Microwaves"], a: 2 },
{ q: "Which EM waves are used in optical fibres?", o: ["Radio waves", "Microwaves", "Visible and infrared", "Ultraviolet"], a: 2 },
{ q: "Which EM waves are used for communication with satellites?", o: ["Radio waves", "Microwaves", "Infrared", "Visible"], a: 1 },
{ q: "EM waves carry", o: ["Only energy", "Only momentum", "Both energy and momentum", "Neither"], a: 2 },
{ q: "EM waves exert pressure called", o: ["Magnetic pressure", "Electric pressure", "Radiation pressure", "Wave pressure"], a: 2 },

{ q: "EM waves do not require", o: ["Frequency", "Wavelength", "Medium", "Energy"], a: 2 },
{ q: "Which EM waves are used in microwave oven?", o: ["Radio waves", "Infrared", "Microwaves", "X-rays"], a: 2 },
{ q: "Which EM waves are used in photography?", o: ["Infrared", "Ultraviolet", "Visible light", "Gamma rays"], a: 2 },
{ q: "The direction of propagation of EM wave is given by", o: ["Electric field", "Magnetic field", "E × B", "E + B"], a: 2 },
{ q: "The wavelength of visible light lies in the range", o: ["400–700 nm", "700–1000 nm", "10–400 nm", "1–10 nm"], a: 0 },
{ q: "Which EM waves are reflected by ionosphere?", o: ["Microwaves", "Infrared", "Radio waves", "X-rays"], a: 2 },
{ q: "Which EM waves are used in remote sensing?", o: ["Infrared", "Ultraviolet", "Visible", "Gamma rays"], a: 0 },
{ q: "Which EM waves have maximum wavelength?", o: ["Radio waves", "Microwaves", "Infrared", "X-rays"], a: 0 },
{ q: "EM spectrum was experimentally verified by", o: ["Maxwell", "Hertz", "Newton", "Planck"], a: 1 },
{ q: "Which EM waves are used in laser?", o: ["Radio", "Microwave", "Infrared / Visible", "X-rays"], a: 2 },

{ q: "The frequency of EM wave increases from", o: ["Gamma → Radio", "Radio → Gamma", "Infrared → Radio", "Visible → Radio"], a: 1 },
{ q: "Which EM waves are harmful to living cells?", o: ["Infrared", "Visible", "Ultraviolet, X-rays, Gamma rays", "Radio waves"], a: 2 },
{ q: "EM waves are unaffected by", o: ["Electric field", "Magnetic field", "Both", "None"], a: 2 },
{ q: "The energy of EM wave depends on", o: ["Amplitude", "Frequency", "Speed", "Medium"], a: 1 },
{ q: "EM waves obey", o: ["Newton’s laws", "Maxwell’s equations", "Ohm’s law", "Faraday’s law"], a: 1 },
{ q: "Electric field vector in EM wave is along", o: ["Direction of propagation", "Magnetic field", "Perpendicular to direction of propagation", "None"], a: 2 },
{ q: "Magnetic field vector in EM wave is along", o: ["Direction of propagation", "Electric field", "Perpendicular to direction of propagation", "Same direction as E"], a: 2 },
{ q: "Which EM waves are used in cancer treatment?", o: ["Infrared", "Ultraviolet", "Gamma rays", "Microwaves"], a: 2 },
{ q: "EM waves are examples of", o: ["Mechanical waves", "Matter waves", "Non-mechanical waves", "Sound waves"], a: 2 },
{ q: "The momentum of EM wave is related to energy by", o: ["p = E", "p = E/c", "p = cE", "p = mc"], a: 1 },

{ q: "EM waves transfer energy through", o: ["Conduction", "Convection", "Radiation", "Induction"], a: 2 },
{ q: "Which EM waves are used in wireless communication?", o: ["Radio waves", "Infrared", "X-rays", "Gamma rays"], a: 0 },
{ q: "Heating effect in sunlight is due to", o: ["UV rays", "IR rays", "Gamma rays", "Radio waves"], a: 1 },
{ q: "Which EM waves are used in spectroscopy?", o: ["Radio waves", "Infrared", "UV & Visible", "All"], a: 3 },
{ q: "Which EM waves are scattered most in atmosphere?", o: ["Radio waves", "Infrared", "Visible light", "Gamma rays"], a: 2 },
{ q: "The Poynting vector represents", o: ["Energy density", "Power flow", "Momentum", "Pressure"], a: 1 },
{ q: "EM waves consist of", o: ["Only electric field", "Only magnetic field", "Both electric and magnetic fields", "Charges"], a: 2 },
{ q: "Which EM waves are used in astronomical observations?", o: ["Radio waves", "Infrared", "X-rays", "All"], a: 3 },
{ q: "Which EM waves have least penetrating power?", o: ["Radio waves", "Infrared", "Ultraviolet", "Gamma rays"], a: 0 },
{ q: "EM waves travel fastest in", o: ["Water", "Glass", "Vacuum", "Air"], a: 2 }
];
