const questions = [
  { q: "The energy gap in a semiconductor is of the order of", o: ["10 eV", "5 eV", "1 eV", "0 eV"], a: 2 },
  { q: "At absolute zero temperature, a semiconductor behaves like", o: ["Conductor", "Insulator", "Semiconductor", "Superconductor"], a: 1 },
  { q: "The charge carriers in intrinsic semiconductor are", o: ["Only electrons", "Only holes", "Electrons and holes", "Protons"], a: 2 },
  { q: "Example of intrinsic semiconductor is", o: ["Doped silicon", "Doped germanium", "Pure silicon", "Copper"], a: 2 },
  { q: "Semiconductor formed by doping with pentavalent impurity is", o: ["p-type", "n-type", "Intrinsic", "Insulator"], a: 1 },
  { q: "Majority charge carriers in n-type semiconductor are", o: ["Holes", "Protons", "Electrons", "Neutrons"], a: 2 },
  { q: "Trivalent impurity is added to form", o: ["n-type semiconductor", "p-type semiconductor", "Intrinsic semiconductor", "Insulator"], a: 1 },
  { q: "Majority charge carriers in p-type semiconductor are", o: ["Electrons", "Holes", "Ions", "Neutrons"], a: 1 },
  { q: "Example of pentavalent impurity is", o: ["Boron", "Aluminium", "Phosphorus", "Indium"], a: 2 },
  { q: "Example of trivalent impurity is", o: ["Arsenic", "Antimony", "Boron", "Phosphorus"], a: 2 },
  { q: "p-n junction is formed by", o: ["Heating semiconductor", "Joining p-type and n-type semiconductors", "Cooling semiconductor", "Applying voltage"], a: 1 },
  { q: "Depletion layer contains", o: ["Free electrons", "Free holes", "Immobile ions", "Neutral atoms"], a: 2 },
  { q: "Potential barrier in p-n junction is due to", o: ["Diffusion of carriers", "Drift of carriers", "Recombination", "External voltage"], a: 0 },
  { q: "Width of depletion layer increases when junction is", o: ["Forward biased", "Reverse biased", "Unbiased", "Heated"], a: 1 },
  { q: "In forward bias, p-side is connected to", o: ["Negative terminal", "Positive terminal", "Ground", "Neutral terminal"], a: 1 },
  { q: "Forward biased p-n junction offers", o: ["High resistance", "Infinite resistance", "Low resistance", "Zero resistance"], a: 2 },
  { q: "Reverse biased p-n junction acts as", o: ["Conductor", "Capacitor", "Insulator", "Amplifier"], a: 2 },
  { q: "Zener diode is used as", o: ["Amplifier", "Rectifier", "Voltage regulator", "Oscillator"], a: 2 },
  { q: "Zener breakdown occurs due to", o: ["Heating", "High reverse voltage", "Forward current", "Low temperature"], a: 1 },
  { q: "A diode conducts current mainly in", o: ["Both directions", "Forward direction", "Reverse direction", "Random direction"], a: 1 },
  { q: "Half-wave rectifier uses", o: ["Two diodes", "Four diodes", "One diode", "No diode"], a: 2 },
  { q: "Full-wave rectifier converts", o: ["AC to DC", "DC to AC", "High voltage to low", "Low voltage to high"], a: 0 },
  { q: "Ripple factor is minimum for", o: ["Half-wave rectifier", "Full-wave rectifier", "No rectifier", "Zener diode"], a: 1 },
  { q: "Transistor has how many layers?", o: ["One", "Two", "Three", "Four"], a: 2 },
  { q: "Transistor has how many junctions?", o: ["One", "Two", "Three", "Four"], a: 1 },
  { q: "The three regions of a transistor are", o: ["Anode, cathode, grid", "Source, drain, gate", "Emitter, base, collector", "p, n, i"], a: 2 },
  { q: "Base of a transistor is", o: ["Thick and highly doped", "Thin and lightly doped", "Thick and lightly doped", "Thin and highly doped"], a: 1 },
  { q: "Main function of transistor is", o: ["Rectification", "Amplification", "Heating", "Cooling"], a: 1 },
  { q: "In common emitter configuration, current gain is", o: ["Less than 1", "Equal to 1", "Greater than 1", "Zero"], a: 2 },
  { q: "Logic gate that gives HIGH output only when all inputs are HIGH is", o: ["OR", "AND", "NOT", "NAND"], a: 1 },
  { q: "NOT gate is also called", o: ["Buffer", "Inverter", "Rectifier", "Amplifier"], a: 1 },
  { q: "NAND gate is known as", o: ["Universal gate", "Basic gate", "Exclusive gate", "Negative gate"], a: 0 },
  { q: "LED emits light due to", o: ["Heating", "Recombination of electrons and holes", "Magnetic effect", "Photoelectric effect"], a: 1 },
  { q: "Solar cell works on", o: ["Thermionic effect", "Photoelectric effect", "Photovoltaic effect", "Hall effect"], a: 2 },
  { q: "Semiconductor devices are preferred because they are", o: ["Bulky", "Power consuming", "Reliable and compact", "Expensive"], a: 2 }
];
