const questions = [
  { q: "A solution is a homogeneous mixture of", o: ["Two solids", "Solute and solvent", "Only liquids", "Only gases"], a: 1 },
  { q: "The component present in larger amount in a solution is called", o: ["Solute", "Solvent", "Dispersed phase", "Medium"], a: 1 },
  { q: "Molality of a solution depends upon", o: ["Volume of solution", "Temperature", "Mass of solvent", "Pressure"], a: 2 },
  { q: "Molarity of a solution changes with", o: ["Pressure", "Temperature", "Mass of solute", "Nature of solute"], a: 1 },
  { q: "Unit of molarity is", o: ["mol kg⁻¹", "mol L⁻¹", "g L⁻¹", "mol m⁻³"], a: 1 },
  { q: "Unit of molality is", o: ["mol L⁻¹", "mol kg⁻¹", "g mol⁻¹", "kg mol⁻¹"], a: 1 },
  { q: "Mole fraction of solvent in an ideal solution is", o: ["Zero", "Less than 1", "Equal to 1", "Greater than 1"], a: 1 },
  { q: "For an ideal solution, which law is obeyed?", o: ["Henry’s law", "Raoult’s law", "Dalton’s law", "Boyle’s law"], a: 1 },
  { q: "Raoult’s law is applicable to", o: ["Non-volatile solute", "Volatile solute", "Ideal solutions", "Colloids"], a: 2 },
  { q: "Vapour pressure of a solution is always", o: ["Greater than solvent", "Equal to solvent", "Less than solvent", "Zero"], a: 2 },

  { q: "Relative lowering of vapour pressure depends upon", o: ["Nature of solute", "Nature of solvent", "Number of solute particles", "Temperature"], a: 2 },
  { q: "Colligative properties depend on", o: ["Size of particles", "Nature of solute", "Number of solute particles", "Shape of solute"], a: 2 },
  { q: "Which is NOT a colligative property?", o: ["Osmotic pressure", "Elevation of boiling point", "Depression of freezing point", "Vapour pressure"], a: 3 },
  { q: "Elevation in boiling point is directly proportional to", o: ["Molality", "Molarity", "Mole fraction", "Normality"], a: 0 },
  { q: "Depression in freezing point is expressed as", o: ["ΔTf = Kf m", "ΔTb = Kb m", "π = CRT", "p = p⁰x"], a: 0 },
  { q: "Boiling point elevation constant is called", o: ["Ebullioscopic constant", "Cryoscopic constant", "Osmotic constant", "Henry’s constant"], a: 0 },
  { q: "Freezing point depression constant is called", o: ["Ebullioscopic constant", "Cryoscopic constant", "Gas constant", "Henry’s constant"], a: 1 },
  { q: "Osmotic pressure is measured using", o: ["Semipermeable membrane", "Permeable membrane", "Metal membrane", "Plastic membrane"], a: 0 },
  { q: "Osmotic pressure is directly proportional to", o: ["Temperature", "Volume", "Pressure", "Density"], a: 0 },
  { q: "Unit of osmotic pressure is", o: ["atm", "mol", "L", "kg"], a: 0 },

  { q: "Van’t Hoff factor (i) is equal to", o: ["0", "1", "Number of particles after dissociation", "Molecular mass"], a: 2 },
  { q: "For non-electrolytes, Van’t Hoff factor is", o: ["0", "< 1", "> 1", "1"], a: 3 },
  { q: "Association of solute particles leads to", o: ["Increase in i", "Decrease in i", "No change in i", "Infinite i"], a: 1 },
  { q: "Dissociation of solute particles causes", o: ["Decrease in colligative property", "Increase in colligative property", "No effect", "Zero osmotic pressure"], a: 1 },
  { q: "Henry’s law relates", o: ["Pressure and volume", "Solubility of gas and pressure", "Temperature and pressure", "Density and pressure"], a: 1 },
  { q: "According to Henry’s law, solubility of gas increases with", o: ["Increase in temperature", "Decrease in pressure", "Increase in pressure", "Decrease in volume"], a: 2 },
  { q: "Soda water bottle is opened with a fizz due to", o: ["Increase in pressure", "Decrease in pressure", "Increase in temperature", "Decrease in solubility"], a: 1 },
  { q: "Ideal solution shows", o: ["No heat change on mixing", "Volume contraction", "Volume expansion", "Heat evolution"], a: 0 },
  { q: "Non-ideal solution shows deviation from", o: ["Dalton’s law", "Boyle’s law", "Raoult’s law", "Henry’s law"], a: 2 },

  { q: "Azeotropes are solutions which", o: ["Obey Raoult’s law", "Do not boil", "Boil at constant temperature", "Separate easily"], a: 2 },
  { q: "Maximum boiling azeotrope shows", o: ["Positive deviation", "Negative deviation", "No deviation", "Infinite deviation"], a: 1 },
  { q: "Minimum boiling azeotrope shows", o: ["Positive deviation", "Negative deviation", "No deviation", "Zero deviation"], a: 0 },
  { q: "Which solution shows positive deviation?", o: ["Acetone + Chloroform", "Ethanol + Water", "HCl + Water", "NaCl + Water"], a: 1 },
  { q: "Relative lowering of vapour pressure is equal to", o: ["Mole fraction of solute", "Mole fraction of solvent", "Molality", "Molarity"], a: 0 },
  { q: "Colligative properties are useful to determine", o: ["Density", "Molecular mass", "Volume", "Colour"], a: 1 },
  { q: "Osmotic pressure is most suitable for determining molecular mass of", o: ["Gases", "Liquids", "Solids", "Polymers"], a: 3 },
  { q: "Solution containing same osmotic pressure are called", o: ["Isobaric", "Isotonic", "Isochoric", "Isothermal"], a: 1 },
  { q: "Reverse osmosis is used in", o: ["Distillation", "Desalination", "Filtration", "Chromatography"], a: 1 },

  { q: "Boiling point elevation occurs because", o: ["Vapour pressure decreases", "Vapour pressure increases", "Density decreases", "Density increases"], a: 0 },
  { q: "Freezing point depression occurs because", o: ["Solvent solidifies faster", "Solvent vapour pressure increases", "Solvent vapour pressure decreases", "Solvent density increases"], a: 2 },
  { q: "If i = 2, solute undergoes", o: ["Association", "No change", "Complete dissociation", "Partial association"], a: 2 },
  { q: "For electrolytes, Van’t Hoff factor is", o: ["Always 1", "Less than 1", "Greater than 1", "Zero"], a: 2 },
  { q: "Molarity of pure water is approximately", o: ["18 M", "55.5 M", "1 M", "100 M"], a: 1 },
  { q: "Henry’s law constant depends on", o: ["Nature of gas", "Nature of solvent", "Temperature", "All of these"], a: 3 },
  { q: "Higher value of Henry’s constant indicates", o: ["Higher solubility", "Lower solubility", "No solubility", "Same solubility"], a: 1 },
  { q: "Ideal solutions have", o: ["A–B < A–A", "A–B > A–A", "A–B = A–A", "No interactions"], a: 2 },
  { q: "Which is an example of ideal solution?", o: ["Benzene + Toluene", "Ethanol + Water", "Acetone + Chloroform", "HCl + Water"], a: 0 },

  { q: "Osmotic pressure equation is", o: ["π = CRT", "PV = nRT", "ΔTb = Kb m", "ΔTf = Kf m"], a: 0 },
  { q: "Colligative properties are independent of", o: ["Nature of solvent", "Number of solute particles", "Concentration", "Temperature"], a: 0 },
  { q: "Reverse osmosis works by applying pressure", o: ["Equal to osmotic pressure", "Less than osmotic pressure", "Greater than osmotic pressure", "Zero pressure"], a: 2 }
];
