const questions = [
  { q: "A relation from set A to set B is a subset of", o: ["A × B","B × A","A ∪ B","A ∩ B"], a: 0 },
  { q: "If A = {1, 2} and B = {3, 4}, then A × B is", o: ["{(1,3), (2,4)}","{(3,1), (4,2)}","{(1,3), (1,4), (2,3), (2,4)}","{(3,1), (3,2), (4,1), (4,2)}"], a: 2 },
  { q: "A relation R on a set A is symmetric if", o: ["(a,b) ∈ R ⇒ (b,a) ∈ R","(a,b) ∈ R ⇒ (a,a) ∈ R","(a,b) ∈ R ⇒ (b,b) ∈ R","(a,a) ∈ R ⇒ (b,b) ∈ R"], a: 0 },
  { q: "A relation R on set A is reflexive if", o: ["(a,b) ∈ R for all a,b ∈ A","(a,a) ∈ R for all a ∈ A","(a,b) ∈ R ⇒ (b,a) ∈ R","(a,b) ∈ R ⇒ (a,a) ∈ R"], a: 1 },
  { q: "A relation R on set A is transitive if", o: ["(a,b),(b,c) ∈ R ⇒ (a,c) ∈ R","(a,b) ∈ R ⇒ (b,a) ∈ R","(a,a) ∈ R for all a","(a,b) ∈ R ⇒ (a,a) ∈ R"], a: 0 },
  { q: "A relation which is reflexive, symmetric and transitive is called", o: ["Identity relation","Equivalence relation","Universal relation","Binary relation"], a: 1 },
  { q: "The number of elements in the universal relation on set A having n elements is", o: ["n","n²","2ⁿ","n!"], a: 1 },
  { q: "The identity relation on set A is", o: ["{(a,b): a ≠ b}","{(a,a): a ∈ A}","A × A","∅"], a: 1 },
  { q: "Which of the following is not a function?", o: ["One–one","Many–one","Onto","One–many"], a: 3 },
  { q: "A function f : A → B is one–one if", o: ["Different elements of A have same image","Same elements of A have different images","Different elements of A have different images","All elements of B are images"], a: 2 },
  { q: "A function f : A → B is onto if", o: ["Every element of A has an image","Every element of B has a pre-image","Every element of A has two images","No element of B has pre-image"], a: 1 },
  { q: "A function which is both one–one and onto is called", o: ["Composite","Bijective","Identity","Constant"], a: 1 },
  { q: "If f(x) = 2x + 3, then f(1) is", o: ["3","4","5","6"], a: 2 },
  { q: "The domain of f(x) = √(x − 2) is", o: ["x ≥ 2","x > 2","x ≤ 2","All real numbers"], a: 0 },
  { q: "The range of f(x) = x² is", o: ["All real numbers","x ≥ 0","x ≤ 0","x > 0"], a: 1 },
  { q: "Which of the following is a constant function?", o: ["f(x) = x","f(x) = x²","f(x) = 5","f(x) = 1/x"], a: 2 },
  { q: "The number of functions from a set A with m elements to a set B with n elements is", o: ["mⁿ","nᵐ","m × n","n!"], a: 1 },
  { q: "A many–one function is", o: ["Not a function","Always one–one","A valid function","Always onto"], a: 2 },
  { q: "If f : R → R defined by f(x) = x³, then f is", o: ["One–one but not onto","Onto but not one–one","Neither one–one nor onto","One–one and onto"], a: 3 },
  { q: "The inverse of a function exists if the function is", o: ["Onto","One–one","Bijective","Constant"], a: 2 },
  { q: "If f(x) = x + 1 and g(x) = 2x, then (f ∘ g)(x) is", o: ["2x + 1","x + 2","2x + 2","x + 1"], a: 0 },
  { q: "If f(x) = 2x + 1, then f⁻¹(x) is", o: ["(x − 1)/2","(x + 1)/2","2x − 1","1/(2x)"], a: 0 },
  { q: "The graph of y = f(x) represents a function if it passes", o: ["Horizontal line test","Vertical line test","Slant line test","Circular test"], a: 1 },
  { q: "Which relation is not reflexive?", o: ["{(a,a)}","{(a,b),(b,a)}","{(a,a),(b,b)}","Identity relation"], a: 1 },
  { q: "If A = ∅, then the number of relations on A is", o: ["0","1","2","Infinite"], a: 1 },
  { q: "The empty relation on a non-empty set is", o: ["Reflexive","Symmetric","Transitive","Both symmetric and transitive"], a: 3 },
  { q: "Which of the following is an equivalence relation?", o: ["≤","<","=","≥"], a: 2 },
  { q: "A relation which relates every element to every element is called", o: ["Identity relation","Universal relation","Empty relation","Equivalence relation"], a: 1 },
  { q: "The domain of the function f(x) = 1/(x − 3) is", o: ["x = 3","x ≠ 3","x ≥ 3","All real numbers"], a: 1 },
  { q: "The range of f(x) = 1/x is", o: ["All real numbers","x > 0","x ≠ 0","x < 0"], a: 2 },
  { q: "A function f : A → B is called injective if it is", o: ["Onto","One–one","Many–one","Constant"], a: 1 },
  { q: "A function f : A → B is surjective if it is", o: ["One–one","Onto","Bijective","Constant"], a: 1 },
  { q: "If f(x) = |x|, then f is", o: ["One–one","Onto","Many–one","Bijective"], a: 2 },
  { q: "The number of equivalence relations on a set with one element is", o: ["0","1","2","Infinite"], a: 1 },
  { q: "The codomain of a function is", o: ["Set of inputs","Set of outputs actually obtained","Set in which all outputs lie","Intersection of domain and range"], a: 2 }
];
