const questions = [
  { q: "Integration is the inverse process of", o: ["Differentiation","Continuity","Limits","Functions"], a: 0 },
  { q: "∫ xⁿ dx (n ≠ −1) equals", o: ["xⁿ⁺¹/n + C","xⁿ⁺¹/(n + 1) + C","nxⁿ⁻¹ + C","1/x + C"], a: 1 },
  { q: "∫ 1/x dx equals", o: ["x + C","ln x + C","eˣ + C","1/x² + C"], a: 1 },
  { q: "∫ eˣ dx equals", o: ["eˣ + C","xeˣ + C","ln x + C","1/eˣ + C"], a: 0 },
  { q: "∫ sin x dx equals", o: ["cos x + C","−cos x + C","−sin x + C","sin x + C"], a: 1 },
  { q: "∫ cos x dx equals", o: ["sin x + C","−sin x + C","tan x + C","sec x + C"], a: 0 },
  { q: "∫ sec²x dx equals", o: ["sec x + C","tan x + C","cosec x + C","sec x tan x + C"], a: 1 },
  { q: "∫ cosec²x dx equals", o: ["−cosec x + C","tan x + C","−cot x + C","cot x + C"], a: 2 },
  { q: "∫ sec x tan x dx equals", o: ["sec x + C","tan x + C","cosec x + C","−sec x + C"], a: 0 },
  { q: "∫ cosec x cot x dx equals", o: ["cosec x + C","−cosec x + C","tan x + C","−tan x + C"], a: 1 },
  { q: "∫ tan x dx equals", o: ["ln|sec x| + C","ln|cos x| + C","ln|sec x + tan x| + C","sec²x + C"], a: 2 },
  { q: "∫ cot x dx equals", o: ["ln|sin x| + C","ln|cosec x| + C","ln|tan x| + C","ln|cosec x − cot x| + C"], a: 0 },
  { q: "∫ sec x dx equals", o: ["ln|sec x + tan x| + C","ln|sec x − tan x| + C","tan x + C","sec²x + C"], a: 0 },
  { q: "∫ cosec x dx equals", o: ["ln|cosec x + cot x| + C","ln|cosec x − cot x| + C","tan x + C","sec x + C"], a: 1 },
  { q: "∫ dx / (1 + x²) equals", o: ["tan x + C","cot x + C","tan⁻¹x + C","sin⁻¹x + C"], a: 2 },
  { q: "∫ dx / √(1 − x²) equals", o: ["tan⁻¹x + C","sin⁻¹x + C","cos⁻¹x + C","sec⁻¹x + C"], a: 1 },
  { q: "∫ dx / (a² + x²) equals", o: ["tan⁻¹(x/a)/a + C","tan⁻¹(ax) + C","sin⁻¹(x/a) + C","sec⁻¹(x/a) + C"], a: 0 },
  { q: "∫ dx / √(a² − x²) equals", o: ["tan⁻¹(x/a) + C","sin⁻¹(x/a) + C","cos⁻¹(x/a) + C","sec⁻¹(x/a) + C"], a: 1 },
  { q: "∫ dx / (x² − a²) equals", o: ["1/a ln|(x − a)/(x + a)| + C","ln|x − a| + C","tan⁻¹(x/a) + C","sec⁻¹(x/a) + C"], a: 0 },
  { q: "∫ dx / (a² − x²) equals", o: ["1/a ln|(a + x)/(a − x)| + C","tan⁻¹(x/a) + C","ln|x| + C","sin⁻¹(x/a) + C"], a: 0 },
  { q: "Integration by parts formula is", o: ["∫u dv = uv − ∫v du","∫u dv = u + v","∫u dv = uv","∫u dv = ∫v du"], a: 0 },
  { q: "In integration by parts, the choice of u is generally based on", o: ["ILATE rule","BODMAS","PEMDAS","DMAS"], a: 0 },
  { q: "In ∫ x eˣ dx, choose u as", o: ["x","eˣ","dx","1"], a: 0 },
  { q: "∫ e²ˣ dx equals", o: ["e²ˣ + C","2e²ˣ + C","½ e²ˣ + C","xe²ˣ + C"], a: 2 },
  { q: "∫ sin²x dx equals", o: ["(x − sin 2x)/2 + C","(x + sin 2x)/2 + C","(x − sin x)/2 + C","(x + sin x)/2 + C"], a: 0 },
  { q: "∫ cos²x dx equals", o: ["(x − sin 2x)/2 + C","(x + sin 2x)/2 + C","(x − cos 2x)/2 + C","(x + cos 2x)/2 + C"], a: 1 },
  { q: "∫ tan²x dx equals", o: ["tan x − x + C","x − tan x + C","sec²x + C","tan²x + C"], a: 0 },
  { q: "∫ sec²x dx equals", o: ["sec x + C","tan x + C","cot x + C","cosec x + C"], a: 1 },
  { q: "∫ (1 + tan²x) dx equals", o: ["x + tan x + C","sec²x + C","tan x + C","x + C"], a: 0 },
  { q: "The constant of integration represents", o: ["Slope","Area","Family of curves","Tangent"], a: 2 },
  { q: "∫ 0 dx equals", o: ["0","C","1","Undefined"], a: 1 },
  { q: "Integration of a function gives", o: ["Unique function","Family of functions","Constant","Zero"], a: 1 },
  { q: "∫ f(ax) dx equals", o: ["f(x) + C","(1/a)F(ax) + C","aF(x) + C","F(x/a) + C"], a: 1 },
  { q: "Substitution method is used when", o: ["Product of functions","Function inside another function","Trigonometric identities","Rational functions"], a: 1 },
  { q: "∫ x dx equals", o: ["x² + C","x²/2 + C","x + C","ln x + C"], a: 1 }
];
