const questions = [
  { q: "The area under a curve y = f(x) between x = a and x = b is given by", o: ["∫ₐᵇ f(x) dx","∫ₐᵇ |f(x)| dx","∫ᵇₐ f(x) dx","f(b) − f(a)"], a: 1 },
  { q: "The area of a region above the x-axis is always", o: ["Negative","Zero","Positive","Undefined"], a: 2 },
  { q: "If a curve lies below the x-axis between a and b, then area is", o: ["∫ₐᵇ f(x) dx","−∫ₐᵇ f(x) dx","∫ᵇₐ f(x) dx","0"], a: 1 },
  { q: "The area between the curve y = f(x), x-axis and lines x = a, x = b is", o: ["∫ₐᵇ f(x) dx","∫ₐᵇ |f(x)| dx","f(b) − f(a)","∫ₐᵇ x dx"], a: 1 },
  { q: "If f(x) ≥ 0 in [a, b], then area is equal to", o: ["∫ₐᵇ f(x) dx","−∫ₐᵇ f(x) dx","∫ᵇₐ f(x) dx","|f(b) − f(a)|"], a: 0 },
  { q: "The area between two curves y = f(x) and y = g(x) (f ≥ g) from a to b is", o: ["∫ₐᵇ [f(x) − g(x)] dx","∫ₐᵇ [g(x) − f(x)] dx","∫ₐᵇ [f(x) + g(x)] dx","∫ₐᵇ f(x)g(x) dx"], a: 0 },
  { q: "The area between curves is measured", o: ["Vertically","Horizontally","Diagonally","Arbitrarily"], a: 0 },
  { q: "The area between x = g(y) and x = f(y) is given by", o: ["∫ [f(y) − g(y)] dy","∫ [g(y) − f(y)] dy","∫ f(y)g(y) dy","∫ dy"], a: 0 },
  { q: "The limits of integration for area are obtained from", o: ["y-intercepts","x-intercepts","Slopes","Curvature"], a: 1 },
  { q: "The region bounded by y = x² and x-axis lies between", o: ["x = −1 to 1","x = 0 to 1","x = −∞ to ∞","x = −2 to 2"], a: 0 },
  { q: "The area between y = x and y = x² is calculated by integrating", o: ["x − x²","x² − x","x + x²","x²/x"], a: 0 },
  { q: "If two curves intersect at x = a and x = b, then area is taken between", o: ["a and b","0 and a","b and ∞","−∞ and ∞"], a: 0 },
  { q: "The area enclosed between x = y² and y = x² is found by", o: ["Integrating w.r.t. x","Integrating w.r.t. y","Integrating either x or y","Differentiation"], a: 1 },
  { q: "If region is symmetrical about y-axis, area is", o: ["Twice the area of one half","Zero","Same as one half","Infinite"], a: 0 },
  { q: "The area between x = a and x = b under y = c (constant) is", o: ["bc","c(b − a)","ab","(b + a)c"], a: 1 },
  { q: "The area of a rectangle using integration is", o: ["∫ₐᵇ c dx","∫ₐᵇ x dx","∫ₐᵇ x² dx","∫ₐᵇ sin x dx"], a: 0 },
  { q: "The unit of area is", o: ["cm","cm²","cm³","unitless"], a: 1 },
  { q: "If the limits are reversed, the integral", o: ["Becomes same","Becomes zero","Changes sign","Doubles"], a: 2 },
  { q: "The area enclosed by a closed curve is always", o: ["Negative","Positive","Zero","Infinite"], a: 1 },
  { q: "The area between x = 0 and y = f(x) is found by integrating", o: ["dy","dx","d²x","d²y"], a: 1 },
  { q: "If y = f(x) is below x-axis in [a, b], then area equals", o: ["∫ₐᵇ f(x) dx","−∫ₐᵇ f(x) dx","∫ᵇₐ f(x) dx","f(b) − f(a)"], a: 1 },
  { q: "The region bounded by x = y² and x = 4 is", o: ["Open","Unbounded","Closed","Infinite"], a: 2 },
  { q: "The area between curves is independent of", o: ["Limits","Curves","Orientation","Axis"], a: 2 },
  { q: "The first step to find area is", o: ["Draw rough sketch","Integrate","Find derivative","Simplify equation"], a: 0 },
  { q: "The area between y = sin x and x-axis from 0 to π is", o: ["0","1","2","π"], a: 2 },
  { q: "If f(x) = g(x) at x = a and x = b, then", o: ["Curves touch","Curves intersect","Area is zero","No area"], a: 1 },
  { q: "The area between curves is maximum when", o: ["Difference is maximum","Difference is minimum","Curves coincide","Area is zero"], a: 0 },
  { q: "The integrand for area between curves is", o: ["f(x) + g(x)","f(x) − g(x)","f(x)g(x)","f′(x)"], a: 1 },
  { q: "The area under a curve is always measured from", o: ["y-axis","x-axis","Origin","Any point"], a: 1 },
  { q: "If the curve cuts x-axis at x = a and x = b, then limits are", o: ["a to b","−a to b","0 to a","0 to b"], a: 0 },
  { q: "The area of region bounded by y = x² and y = 4 is", o: ["∫(4 − x²) dx","∫(x² − 4) dx","∫(4 + x²) dx","∫4x² dx"], a: 0 },
  { q: "Area is a", o: ["Vector quantity","Scalar quantity","Tensor","Dimensionless"], a: 1 },
  { q: "The unit of definite integral representing area is", o: ["cm","cm²","cm³","unitless"], a: 1 },
  { q: "If two curves do not intersect, area between them is", o: ["Zero","Infinite","Not defined","Always finite"], a: 2 },
  { q: "The method of applications of integrals is mainly used to find", o: ["Length","Area","Volume","Slope"], a: 1 }
];
