const questions = [
  { q: "A differential equation contains", o: ["Only variables","Only constants","Derivatives","Integrals"], a: 2 },
  { q: "The order of the differential equation d²y/dx² + 3 dy/dx + y = 0 is", o: ["1","2","3","0"], a: 1 },
  { q: "The degree of the differential equation (dy/dx)³ + y = 0 is", o: ["1","2","3","Not defined"], a: 2 },
  { q: "The degree of a differential equation is defined only when", o: ["It is linear","It is polynomial in derivatives","It has constants","It has variables"], a: 1 },
  { q: "Which of the following is a first-order differential equation?", o: ["d²y/dx² = x","dy/dx = x + y","d³y/dx³ = y","y = x²"], a: 1 },
  { q: "The general solution of a differential equation contains", o: ["One constant","No constant","Arbitrary constants","Variables only"], a: 2 },
  { q: "The solution which satisfies given conditions is called", o: ["General solution","Particular solution","Singular solution","Linear solution"], a: 1 },
  { q: "The differential equation dy/dx = f(x) is solved by", o: ["Differentiation","Integration","Substitution","Elimination"], a: 1 },
  { q: "The solution of dy/dx = 3x² is", o: ["y = x³ + C","y = 3x³ + C","y = x² + C","y = 6x + C"], a: 0 },
  { q: "A variable separable differential equation can be written as", o: ["dy + dx = 0","f(y)dy = g(x)dx","dy/dx = 0","y = mx + c"], a: 1 },
  { q: "The equation dy/dx = y/x is", o: ["Linear","Homogeneous","Exact","Partial"], a: 1 },
  { q: "The solution of dy/dx = y/x is", o: ["y² = x² + C","y = x + C","y² + x² = C","y = x² + C"], a: 0 },
  { q: "A linear differential equation is of the form", o: ["dy/dx = xy","dy/dx + Py = Q","dy/dx + y² = x","d²y/dx² + y = 0"], a: 1 },
  { q: "The integrating factor (I.F.) of dy/dx + Py = Q is", o: ["e^P","e^(∫Pdx)","e^Q","Pdx"], a: 1 },
  { q: "The integrating factor of dy/dx + y = x is", o: ["e^x","e^-x","x","1/x"], a: 0 },
  { q: "Order of the equation (dy/dx)² + y = 0 is", o: ["1","2","Not defined","0"], a: 0 },
  { q: "Degree of dy/dx + y = 0 is", o: ["1","2","½","Not defined"], a: 3 },
  { q: "A differential equation represents", o: ["A family of curves","A single curve","A point","A straight line only"], a: 0 },
  { q: "The solution of dy/dx = ky is", o: ["y = kx + C","y = Ce^(kx)","y = x^k + C","y = k + C"], a: 1 },
  { q: "Which method is used for solving linear differential equations?", o: ["Separation of variables","Integrating factor","Substitution","Elimination"], a: 1 },
  { q: "The number of arbitrary constants in the general solution equals", o: ["Degree","Order","Variables","Coefficients"], a: 1 },
  { q: "The equation dy/dx = y/x is solved by", o: ["Linear method","Homogeneous method","Exact method","Partial method"], a: 1 },
  { q: "A differential equation having variables separable is always", o: ["Linear","Non-linear","Solvable","Exact"], a: 2 },
  { q: "Which of the following is not a differential equation?", o: ["dy/dx = x","d²y/dx² + y = 0","y = x²","dy/dx + y = 1"], a: 2 },
  { q: "The solution of dy/dx = 0 is", o: ["y = 0","y = C","y = x","y = x²"], a: 1 },
  { q: "If order = degree, the equation is", o: ["Linear","Homogeneous","Simple","Well defined"], a: 3 },
  { q: "Which chapter comes after Differential Equations in NCERT?", o: ["Vectors","Probability","Matrices","Integrals"], a: 1 },
  { q: "Differential equations are used to solve problems related to", o: ["Motion","Growth and decay","Electricity","All of these"], a: 3 },
  { q: "A differential equation of order zero is", o: ["y = x","dy/dx = 1","d²y/dx² = 0","dy = 0"], a: 0 },
  { q: "The integrating factor depends on", o: ["x only","y only","Both x and y","Constants"], a: 0 },
  { q: "The equation dy/dx + y tanx = sinx is", o: ["Non-linear","Homogeneous","Linear","Exact"], a: 2 },
  { q: "The solution of a differential equation is obtained by", o: ["Differentiation","Integration","Factorization","Substitution only"], a: 1 },
  { q: "The equation of motion in physics is a", o: ["Algebraic equation","Differential equation","Trigonometric equation","Quadratic equation"], a: 1 },
  { q: "The differential equation of family of circles is of order", o: ["1","2","3","0"], a: 0 },
  { q: "Differential equations help in finding", o: ["Relations","Unknown functions","Constants","Coordinates"], a: 1 }
];
