const questions = [
  { q: "A vector having both magnitude and direction is called", o: ["Scalar","Vector","Tensor","Unit"], a: 1 },
  { q: "Which of the following is a scalar quantity?", o: ["Velocity","Displacement","Acceleration","Mass"], a: 3 },
  { q: "The magnitude of vector a = 3i + 4j is", o: ["5","7","1","25"], a: 0 },
  { q: "A unit vector has magnitude", o: ["0","1","2","∞"], a: 1 },
  { q: "The unit vector in the direction of vector a is", o: ["a","a²","a/|a|","|a|"], a: 2 },
  { q: "If a = i + j + k, then |a| is", o: ["1","√2","√3","3"], a: 2 },
  { q: "Two vectors are equal if", o: ["They have same magnitude","They have same direction","They have same magnitude and direction","They lie in same plane"], a: 2 },
  { q: "The zero vector has", o: ["Only direction","Only magnitude","Neither magnitude nor direction","Infinite magnitude"], a: 2 },
  { q: "If a + b = 0, then", o: ["a = b","a = −b","a = 2b","a · b = 0"], a: 1 },
  { q: "The angle between two perpendicular vectors is", o: ["0°","45°","90°","180°"], a: 2 },
  { q: "The dot product of two perpendicular vectors is", o: ["1","Maximum","Zero","Minimum"], a: 2 },
  { q: "The scalar product of a and b is", o: ["Vector","Scalar","Tensor","Unit vector"], a: 1 },
  { q: "Formula for dot product is", o: ["a · b = ab","ab sinθ","ab cosθ","a + b"], a: 2 },
  { q: "If a · b = 0, then vectors are", o: ["Parallel","Collinear","Perpendicular","Equal"], a: 2 },
  { q: "The cross product of two vectors is a", o: ["Scalar","Vector","Number","Matrix"], a: 1 },
  { q: "The direction of cross product is given by", o: ["Left-hand rule","Right-hand thumb rule","Fleming’s left-hand rule","Fleming’s right-hand rule"], a: 1 },
  { q: "Magnitude of a × b is", o: ["ab cosθ","ab sinθ","a + b","a − b"], a: 1 },
  { q: "The vector product of parallel vectors is", o: ["Maximum","Minimum","Zero","1"], a: 2 },
  { q: "The vector product of a vector with itself is", o: ["1","Vector","Scalar","Zero"], a: 3 },
  { q: "i × j =", o: ["i","j","k","0"], a: 2 },
  { q: "j × i =", o: ["k","−k","i","0"], a: 1 },
  { q: "i · j =", o: ["1","–1","0","2"], a: 2 },
  { q: "Scalar triple product gives", o: ["Area","Volume","Length","Angle"], a: 1 },
  { q: "If scalar triple product is zero, then vectors are", o: ["Parallel","Perpendicular","Coplanar","Equal"], a: 2 },
  { q: "The position vector of origin is", o: ["i","j","k","Zero vector"], a: 3 },
  { q: "The position vector of point (x, y, z) is", o: ["x+y+z","x i + y j + z k","i + j + k","xyz"], a: 1 },
  { q: "Two vectors are collinear if", o: ["Their dot product is zero","Their cross product is zero","They are perpendicular","They are unit vectors"], a: 1 },
  { q: "The area of parallelogram formed by vectors is given by", o: ["a · b","|a × b|","|a + b|","ab cosθ"], a: 1 },
  { q: "The projection of a on b is", o: ["a sinθ","a cosθ","b sinθ","b cosθ"], a: 1 },
  { q: "If a and b are unit vectors, then a · b equals", o: ["1","cosθ","sinθ","0"], a: 1 },
  { q: "The magnitude of zero vector is", o: ["0","1","∞","Undefined"], a: 0 },
  { q: "If vectors are anti-parallel, angle between them is", o: ["0°","45°","90°","180°"], a: 3 },
  { q: "Vector algebra is useful in", o: ["Geometry","Physics","Engineering","All of these"], a: 3 },
  { q: "The dot product is distributive over", o: ["Scalar multiplication","Vector addition","Vector subtraction","Cross product"], a: 1 },
  { q: "Vector algebra was introduced by", o: ["Newton","Einstein","Hamilton","Maxwell"], a: 2 }
];
