const questions = [
  { q: "Linear programming deals with", o: ["Linear equations only","Linear inequalities only","Optimization of linear objective function","Quadratic equations"], a: 2 },
  { q: "The objective function in LPP is always", o: ["Linear","Quadratic","Cubic","Exponential"], a: 0 },
  { q: "The constraints in LPP are", o: ["Linear equations","Linear inequalities","Non-linear equations","Quadratic inequalities"], a: 1 },
  { q: "The solution of an LPP is obtained by", o: ["Substitution method","Graphical method","Elimination method","Factorization"], a: 1 },
  { q: "The feasible region of an LPP is", o: ["Empty set","Set of all points satisfying objective function","Set of all points satisfying constraints","Only boundary points"], a: 2 },
  { q: "The feasible region is always", o: ["Unbounded","Bounded","Convex","Circular"], a: 2 },
  { q: "The optimal value of objective function occurs at", o: ["Any point","Midpoint","Corner point","Origin only"], a: 2 },
  { q: "The corner point method is used to", o: ["Find feasible region","Find constraints","Find optimal solution","Find objective function"], a: 2 },
  { q: "A feasible solution that optimizes objective function is called", o: ["Feasible solution","Optimal solution","Infeasible solution","Unbounded solution"], a: 1 },
  { q: "The objective function in standard form is", o: ["Z = ax + by","ax + by = 0","ax + by ≥ c","x + y = 0"], a: 0 },
  { q: "Non-negativity constraints are", o: ["x > 0, y > 0","x ≥ 0, y ≥ 0","x ≤ 0, y ≤ 0","x ≠ 0"], a: 1 },
  { q: "The number of constraints in a graphical LPP is", o: ["1","2","At most 2 variables","At most 3 variables"], a: 2 },
  { q: "If the feasible region is unbounded, then optimal solution", o: ["Always exists","Never exists","May or may not exist","Is infinite"], a: 2 },
  { q: "The graphical method can be used when number of variables is", o: ["1","2","3","Any number"], a: 1 },
  { q: "The maximum or minimum value of objective function is called", o: ["Feasible value","Constraint value","Optimal value","Boundary value"], a: 2 },
  { q: "The line ax + by = c is called", o: ["Constraint line","Objective line","Inequality line","Region line"], a: 0 },
  { q: "The feasible region is the intersection of", o: ["Lines","Half planes","Circles","Parabolas"], a: 1 },
  { q: "If constraints are inconsistent, feasible region is", o: ["Unbounded","Empty","Bounded","Convex"], a: 1 },
  { q: "The graphical solution of an LPP is based on", o: ["Geometry","Algebra","Trigonometry","Calculus"], a: 0 },
  { q: "If objective function is parallel to a constraint, then", o: ["No solution","Unique solution","Infinite solutions","Zero solution"], a: 2 },
  { q: "A bounded feasible region always gives", o: ["No solution","One solution","Infinite solutions","Optimal solution"], a: 3 },
  { q: "The feasible region lies in", o: ["All quadrants","First quadrant","Second quadrant","Third quadrant"], a: 1 },
  { q: "The corner points of feasible region are called", o: ["End points","Extreme points","Mid points","Boundary points"], a: 1 },
  { q: "Which of the following is not a constraint?", o: ["x ≥ 0","y ≥ 0","Z = 3x + 4y","x + y ≤ 5"], a: 2 },
  { q: "The objective function represents", o: ["Loss only","Profit or cost","Area only","Volume only"], a: 1 },
  { q: "If feasible region reduces to a point, then", o: ["No solution","Infinite solutions","Unique solution","Unbounded solution"], a: 2 },
  { q: "Linear programming problems are used in", o: ["Business","Industry","Economics","All of these"], a: 3 },
  { q: "The solution of LPP depends on", o: ["Objective function only","Constraints only","Corner points","Variables"], a: 2 },
  { q: "The graph of ax + by ≤ c is", o: ["Line only","Half plane","Circle","Parabola"], a: 1 },
  { q: "The inequality x ≥ 0 represents", o: ["x-axis","y-axis","Right half plane","Left half plane"], a: 2 },
  { q: "The inequality y ≥ 0 represents", o: ["Upper half plane","Lower half plane","Right half plane","Left half plane"], a: 0 },
  { q: "The feasible region is enclosed by", o: ["Curves","Lines","Inequalities","Points"], a: 1 },
  { q: "LPP can have more than one optimal solution when", o: ["Feasible region is bounded","Objective function is parallel to a constraint","Feasible region is unbounded","Constraints are inconsistent"], a: 1 },
  { q: "The corner point method is also known as", o: ["Analytical method","Graphical method","Algebraic method","Numerical method"], a: 1 },
  { q: "Linear programming was developed during", o: ["World War I","World War II","Cold War","Industrial revolution"], a: 1 }
];
