const questions = [
  { q: "Probability of an event lies between", o: ["–1 and 1","0 and 1","1 and 2","–∞ and ∞"], a: 1 },
  { q: "The probability of a sure event is", o: ["0","½","1","–1"], a: 2 },
  { q: "The probability of an impossible event is", o: ["1","0","–1","∞"], a: 1 },
  { q: "If P(A) = 0.35, then P(not A) is", o: ["0.35","0.65","1.35","0"], a: 1 },
  { q: "The sum of probabilities of all possible outcomes is", o: ["0","½","1","Depends on event"], a: 2 },
  { q: "Two events are said to be mutually exclusive if", o: ["They occur together","They have common outcomes","They cannot occur together","They are independent"], a: 2 },
  { q: "For mutually exclusive events A and B", o: ["P(A ∩ B) = 1","P(A ∩ B) = P(A) + P(B)","P(A ∩ B) = 0","P(A ∪ B) = 0"], a: 2 },
  { q: "The formula for probability of union of two events is", o: ["P(A ∩ B)","P(A) + P(B)","P(A) + P(B) − P(A ∩ B)","P(A) − P(B)"], a: 2 },
  { q: "If events A and B are independent, then", o: ["P(A ∩ B) = 0","P(A ∪ B) = 1","P(A ∩ B) = P(A)P(B)","P(A) = P(B)"], a: 2 },
  { q: "Conditional probability P(A|B) is defined as", o: ["P(A)/P(B)","P(B)/P(A)","P(A ∩ B)/P(B)","P(A ∩ B)/P(A)"], a: 2 },
  { q: "Bayes’ theorem is used to find", o: ["Simple probability","Conditional probability","Prior probability","Posterior probability"], a: 3 },
  { q: "The events having no common outcomes are called", o: ["Independent","Complementary","Mutually exclusive","Equally likely"], a: 2 },
  { q: "If two events are independent, then", o: ["P(A|B) = P(A)","P(A|B) = 0","P(A|B) = 1","P(A|B) = P(B)"], a: 0 },
  { q: "The probability of getting a head when tossing a fair coin is", o: ["0","1","½","2"], a: 2 },
  { q: "The probability of getting a number greater than 6 on a die is", o: ["1","½","0","1/6"], a: 2 },
  { q: "If P(A) = 0.4 and P(B) = 0.5 and A, B are independent, then P(A ∩ B) is", o: ["0.9","0.2","0.1","0"], a: 1 },
  { q: "The complement of event A is denoted by", o: ["A′","A²","1/A","A₀"], a: 0 },
  { q: "P(A ∪ A′) is always", o: ["0","½","1","Undefined"], a: 2 },
  { q: "If P(A) = 1, then event A is", o: ["Impossible","Random","Sure","Complementary"], a: 2 },
  { q: "The probability of drawing a red card from a deck of cards is", o: ["1/4","1/13","1/2","3/4"], a: 2 },
  { q: "Total number of cards in a deck is", o: ["26","52","13","4"], a: 1 },
  { q: "The probability of drawing an ace from a deck of cards is", o: ["1/52","4/52","1/13","Both B and C"], a: 3 },
  { q: "Random experiment is one whose outcome", o: ["Is fixed","Is predictable","Cannot be predicted with certainty","Is always same"], a: 2 },
  { q: "Equally likely outcomes means", o: ["Different probabilities","Same probabilities","No probability","Random probabilities"], a: 1 },
  { q: "If A and B are complementary events, then", o: ["A ∪ B = φ","A ∩ B = S","A ∪ B = S","A = B"], a: 2 },
  { q: "Sample space is", o: ["A single outcome","A random event","Set of all possible outcomes","A sure event"], a: 2 },
  { q: "The probability of sample space is", o: ["0","½","1","Depends"], a: 2 },
  { q: "If P(A) + P(B) > 1, then A and B are", o: ["Independent","Mutually exclusive","Not mutually exclusive","Complementary"], a: 2 },
  { q: "Which formula is correct?", o: ["P(A) + P(A′) = 0","P(A) − P(A′) = 1","P(A) + P(A′) = 1","P(A) × P(A′) = 1"], a: 2 },
  { q: "If P(A ∩ B) = P(A)P(B), then A and B are", o: ["Mutually exclusive","Complementary","Independent","Impossible"], a: 2 },
  { q: "Probability theory is widely used in", o: ["Statistics","Physics","Economics","All of these"], a: 3 },
  { q: "The number of possible outcomes when tossing two coins is", o: ["2","3","4","6"], a: 2 },
  { q: "The probability of getting at least one head in two coin tosses is", o: ["1/4","1/2","3/4","1"], a: 2 },
  { q: "If events A and B are mutually exclusive, then", o: ["P(A|B) = P(A)","P(A ∩ B) ≠ 0","P(A ∩ B) = 0","P(A) = P(B)"], a: 2 },
  { q: "Probability helps in predicting", o: ["Past events","Certain events","Chance of occurrence","Fixed outcomes"], a: 2 }
];
