const questions = [
  { q: "The order of a matrix having 3 rows and 2 columns is", o: ["2 × 3","3 × 2","3 × 3","2 × 2"], a: 1 },
  { q: "A matrix having equal number of rows and columns is called", o: ["Row matrix","Column matrix","Square matrix","Rectangular matrix"], a: 2 },
  { q: "A matrix with all elements zero is called", o: ["Identity matrix","Diagonal matrix","Scalar matrix","Zero matrix"], a: 3 },
  { q: "A square matrix A is said to be symmetric if", o: ["A = −A","A = Aᵀ","Aᵀ = −A","|A| = 0"], a: 1 },
  { q: "A square matrix A is skew-symmetric if", o: ["A = Aᵀ","A = −Aᵀ","A = I","|A| = 1"], a: 1 },
  { q: "The transpose of a matrix of order m × n is of order", o: ["m × n","n × m","m × m","n × n"], a: 1 },
  { q: "(Aᵀ)ᵀ is equal to", o: ["−A","A","Aᵀ","I"], a: 1 },
  { q: "If A and B are matrices of same order, then (A + B)ᵀ equals", o: ["Aᵀ + Bᵀ","Aᵀ − Bᵀ","AB","BA"], a: 0 },
  { q: "If A is a matrix of order 2 × 3 and B is 3 × 4, then AB is of order", o: ["2 × 4","3 × 3","4 × 2","2 × 3"], a: 0 },
  { q: "Matrix multiplication is", o: ["Commutative","Associative","Both A and B","Neither A nor B"], a: 1 },
  { q: "For matrices A and B, AB = BA is", o: ["Always true","Always false","Sometimes true","Never defined"], a: 2 },
  { q: "The identity matrix is always a", o: ["Zero matrix","Scalar matrix","Diagonal matrix","Both B and C"], a: 3 },
  { q: "If A is a square matrix, then A·I equals", o: ["I","0","A","Aᵀ"], a: 2 },
  { q: "A diagonal matrix has", o: ["All elements zero","Non-zero diagonal elements only","All elements equal","Only one row"], a: 1 },
  { q: "If A is a 3 × 3 matrix and |A| = 0, then A is", o: ["Non-singular","Singular","Identity","Scalar"], a: 1 },
  { q: "The determinant of identity matrix is", o: ["0","1","−1","Depends on order"], a: 1 },
  { q: "If A is symmetric, then Aᵀ is", o: ["Skew-symmetric","Zero matrix","Symmetric","Identity"], a: 2 },
  { q: "If A is skew-symmetric, then the diagonal elements are", o: ["Positive","Negative","Zero","One"], a: 2 },
  { q: "The matrix which represents reflection is", o: ["Zero matrix","Identity matrix","Orthogonal matrix","Scalar matrix"], a: 2 },
  { q: "If A is a matrix such that A² = A, then A is called", o: ["Involutory","Idempotent","Singular","Nilpotent"], a: 1 },
  { q: "A matrix A is nilpotent if", o: ["A² = A","A² = 0","A = I","|A| = 1"], a: 1 },
  { q: "If A² = I, then A is called", o: ["Singular","Symmetric","Involutory","Nilpotent"], a: 2 },
  { q: "The inverse of identity matrix is", o: ["0","I","−I","Does not exist"], a: 1 },
  { q: "A matrix having only one row is called", o: ["Column matrix","Square matrix","Row matrix","Diagonal matrix"], a: 2 },
  { q: "A matrix having only one column is called", o: ["Row matrix","Column matrix","Scalar matrix","Square matrix"], a: 1 },
  { q: "If A is a non-singular matrix, then A⁻¹ exists", o: ["Always","Never","Sometimes","Only if A is symmetric"], a: 0 },
  { q: "If A is singular, then A⁻¹", o: ["Exists","Does not exist","Equals A","Equals I"], a: 1 },
  { q: "The inverse of a matrix is unique", o: ["True","False","Depends on order","Sometimes"], a: 0 },
  { q: "If A and B are invertible matrices, then (AB)⁻¹ equals", o: ["A⁻¹B⁻¹","B⁻¹A⁻¹","(AB)ᵀ","AᵀBᵀ"], a: 1 },
  { q: "The trace of a square matrix is the", o: ["Product of diagonal elements","Sum of all elements","Sum of diagonal elements","Determinant"], a: 2 },
  { q: "A matrix with all diagonal elements equal and others zero is called", o: ["Identity","Scalar","Diagonal","Zero"], a: 1 },
  { q: "If Aᵀ = −A, then A is", o: ["Symmetric","Orthogonal","Skew-symmetric","Diagonal"], a: 2 },
  { q: "The transpose of identity matrix is", o: ["0","−I","I","A"], a: 2 },
  { q: "If A is a square matrix, then |Aᵀ| equals", o: ["−|A|","|A|","|A|²","1"], a: 1 },
  { q: "The determinant of a skew-symmetric matrix of odd order is", o: ["1","−1","0","Undefined"], a: 2 }
];
