const questions = [
  { q: "A function is said to be continuous at x = a if", o: ["LHL exists","RHL exists","LHL = RHL = f(a)","f(a) is defined"], a: 2 },
  { q: "If a function is differentiable at a point, then it is", o: ["Discontinuous","Continuous","Constant","Not defined"], a: 1 },
  { q: "Which of the following implies continuity but not differentiability?", o: ["Sharp corner","Jump","Hole","Infinite discontinuity"], a: 0 },
  { q: "The derivative of sin x is", o: ["cos x","−cos x","sin x","−sin x"], a: 0 },
  { q: "The derivative of cos x is", o: ["sin x","−sin x","cos x","−cos x"], a: 1 },
  { q: "If f(x) = x³, then f′(x) equals", o: ["3x","x²","3x²","x³"], a: 2 },
  { q: "The derivative of eˣ is", o: ["eˣ","xeˣ","1","ln x"], a: 0 },
  { q: "The derivative of ln x is", o: ["x","1/x","ln x","eˣ"], a: 1 },
  { q: "If f(x) = ax + b, then f′(x) is", o: ["a","b","ax","0"], a: 0 },
  { q: "The derivative of a constant is", o: ["1","Constant","0","Undefined"], a: 2 },
  { q: "If f(x) = x² + 3x + 5, then f′(x) is", o: ["x + 3","2x + 3","2x","3x²"], a: 1 },
  { q: "The derivative of tan x is", o: ["sec²x","cosec²x","sec x","tan²x"], a: 0 },
  { q: "The derivative of cot x is", o: ["cosec²x","−cosec²x","sec²x","−sec²x"], a: 1 },
  { q: "The derivative of sec x is", o: ["sec x tan x","tan x","sec²x","cosec x"], a: 0 },
  { q: "The derivative of cosec x is", o: ["cosec x cot x","sec x tan x","−cosec x cot x","−sec x tan x"], a: 2 },
  { q: "If f(x) = |x|, then f(x) is differentiable at x = 0", o: ["Yes","No","Sometimes","Always"], a: 1 },
  { q: "A function is differentiable at x = a if", o: ["LHD = RHD","LHL = RHL","f(a) exists","f(x) is bounded"], a: 0 },
  { q: "Which function is NOT differentiable at x = 0?", o: ["x²","x³","|x|","x"], a: 2 },
  { q: "The derivative of xⁿ (n ∈ R) is", o: ["nxⁿ","nxⁿ⁻¹","xⁿ⁻¹","n"], a: 1 },
  { q: "The derivative of logₑ x is", o: ["x","1/x","ln x","eˣ"], a: 1 },
  { q: "If f(x) = sin⁻¹x, then domain of f(x) is", o: ["(−∞, ∞)","[−1, 1]","(0, ∞)","(−1, 1)"], a: 1 },
  { q: "The derivative of sin⁻¹x is", o: ["1/√(1 − x²)","1/√(1 + x²)","√(1 − x²)","√(1 + x²)"], a: 0 },
  { q: "The derivative of tan⁻¹x is", o: ["1/(1 − x²)","1/(1 + x²)","√(1 + x²)","√(1 − x²)"], a: 1 },
  { q: "If f(x) is continuous at x = a, then", o: ["f′(a) exists","f(a) exists","f is constant","f is linear"], a: 1 },
  { q: "Which function is continuous everywhere but not differentiable everywhere?", o: ["x²","|x|","sin x","eˣ"], a: 1 },
  { q: "The chain rule is used when", o: ["Two functions are added","Two functions are multiplied","One function is inside another","Function is constant"], a: 2 },
  { q: "The derivative of e²ˣ is", o: ["e²ˣ","2e²ˣ","xe²ˣ","2eˣ"], a: 1 },
  { q: "The derivative of ln(ax) is", o: ["a/x","1/x","ln a","a"], a: 1 },
  { q: "If f(x) = sin x + cos x, then f′(x) equals", o: ["sin x − cos x","cos x − sin x","sin x + cos x","−sin x − cos x"], a: 1 },
  { q: "The derivative of x² sin x is found using", o: ["Chain rule","Quotient rule","Product rule","Log rule"], a: 2 },
  { q: "The product rule states", o: ["(uv)' = u'v'","(uv)' = u'v + uv'","(uv)' = u + v","(uv)' = u/v"], a: 1 },
  { q: "The quotient rule is used when", o: ["Two functions are multiplied","One function is divided by another","Functions are added","Function is constant"], a: 1 },
  { q: "The derivative of x⁻¹ is", o: ["x⁻²","−x⁻²","1/x","−1/x"], a: 1 },
  { q: "If f′(x) = 0 for all x, then f(x) is", o: ["Linear","Quadratic","Constant","Exponential"], a: 2 },
  { q: "Continuity of a function at x = a requires", o: ["Only LHL","Only RHL","Limit exists and equals f(a)","Differentiability"], a: 2 }
];
