const questions = [
  { q: "The rate of change of a quantity is represented by", o: ["Integral","Limit","Derivative","Function"], a: 2 },
  { q: "The slope of the tangent to a curve at a point is given by", o: ["y","dy/dx","dx/dy","∫y dx"], a: 1 },
  { q: "If dy/dx > 0 in an interval, the function is", o: ["Decreasing","Constant","Increasing","Discontinuous"], a: 2 },
  { q: "If dy/dx < 0 in an interval, the function is", o: ["Increasing","Decreasing","Constant","Continuous"], a: 1 },
  { q: "If dy/dx = 0 at x = a, then x = a is", o: ["Point of inflection","Critical point","Discontinuous point","Asymptote"], a: 1 },
  { q: "A point where dy/dx = 0 or dy/dx is not defined is called", o: ["Turning point","Stationary point","Critical point","Inflection point"], a: 2 },
  { q: "A function has a local maximum at x = a if", o: ["f′(a) = 0 and f″(a) > 0","f′(a) = 0 and f″(a) < 0","f′(a) ≠ 0","f″(a) = 0"], a: 1 },
  { q: "A function has a local minimum at x = a if", o: ["f′(a) = 0 and f″(a) > 0","f′(a) = 0 and f″(a) < 0","f′(a) ≠ 0","f″(a) = 0"], a: 0 },
  { q: "If f″(a) = 0, then x = a is", o: ["Maximum point","Minimum point","Inconclusive","Always inflection"], a: 2 },
  { q: "The first derivative test is used to find", o: ["Continuity","Differentiability","Increasing/decreasing nature","Area"], a: 2 },
  { q: "The second derivative test is used to find", o: ["Continuity","Maxima and minima","Area","Slope"], a: 1 },
  { q: "At a point of inflection", o: ["f′(x) = 0","f″(x) changes sign","f′(x) is maximum","f(x) is zero"], a: 1 },
  { q: "If f′(x) changes from +ve to −ve at x = a, then f(x) has", o: ["Local minimum","Local maximum","No extremum","Inflection point"], a: 1 },
  { q: "If f′(x) changes from −ve to +ve at x = a, then f(x) has", o: ["Local maximum","Local minimum","No extremum","Inflection point"], a: 1 },
  { q: "The condition for maxima or minima is", o: ["f′(x) ≠ 0","f′(x) = 0","f″(x) ≠ 0","f(x) = 0"], a: 1 },
  { q: "The equation of tangent to y = f(x) at (a, f(a)) is", o: ["y − a = f′(x)(x − f(a))","y − f(a) = f′(a)(x − a)","y − a = f(a)(x − a)","y = f′(a)x"], a: 1 },
  { q: "The equation of normal to y = f(x) at (a, f(a)) is", o: ["y − f(a) = f′(a)(x − a)","y − f(a) = −1/f′(a) (x − a)","y − a = f′(a)(x − f(a))","y = −f′(a)x"], a: 1 },
  { q: "The angle between tangent and x-axis is θ, then", o: ["tan θ = dy/dx","sin θ = dy/dx","cos θ = dy/dx","θ = dy/dx"], a: 0 },
  { q: "If the tangent is parallel to x-axis, then", o: ["dy/dx = 1","dy/dx = 0","dy/dx = ∞","dy/dx = −1"], a: 1 },
  { q: "If the tangent is perpendicular to x-axis, then", o: ["dy/dx = 0","dy/dx = 1","dy/dx = ∞","dy/dx = −1"], a: 2 },
  { q: "The function f(x) = x³ has at x = 0", o: ["Maximum","Minimum","Point of inflection","Discontinuity"], a: 2 },
  { q: "The function f(x) = x² has at x = 0", o: ["Maximum","Minimum","Inflection","No extremum"], a: 1 },
  { q: "The function f(x) = −x² has at x = 0", o: ["Maximum","Minimum","Inflection","No extremum"], a: 0 },
  { q: "The slope of normal is", o: ["dy/dx","−dy/dx","−1/(dy/dx)","1/(dy/dx)"], a: 2 },
  { q: "If a function is constant in an interval, then", o: ["f′(x) = 1","f′(x) = 0","f′(x) = −1","f′(x) = ∞"], a: 1 },
  { q: "Increasing function means", o: ["dy/dx < 0","dy/dx = 0","dy/dx > 0","dy/dx ≤ 0"], a: 2 },
  { q: "Decreasing function means", o: ["dy/dx > 0","dy/dx < 0","dy/dx = 0","dy/dx ≥ 0"], a: 1 },
  { q: "A stationary point may be", o: ["Only maximum","Only minimum","Only inflection","Maximum, minimum or inflection"], a: 3 },
  { q: "The maximum or minimum value of a function is also called", o: ["Extreme value","Constant value","Mean value","Absolute value"], a: 0 },
  { q: "Optimization problems deal with", o: ["Area only","Volume only","Maximum or minimum values","Continuity"], a: 2 },
  { q: "The first derivative gives information about", o: ["Curvature","Nature of function","Area","Volume"], a: 1 },
  { q: "The second derivative gives information about", o: ["Continuity","Slope","Concavity","Area"], a: 2 },
  { q: "If f″(x) > 0, the curve is", o: ["Concave down","Concave up","Linear","Horizontal"], a: 1 },
  { q: "If f″(x) < 0, the curve is", o: ["Concave up","Linear","Concave down","Horizontal"], a: 2 },
  { q: "The point where concavity changes is called", o: ["Stationary point","Turning point","Inflection point","Critical point"], a: 2 }
];
