// ======= questions.js =======
const questions = [
  { q: "The reproductive part of a flowering plant is", o: ["Root", "Stem", "Leaf", "Flower"], a: 3 },
  { q: "The male reproductive organ of a flower is", o: ["Gynoecium", "Androecium", "Calyx", "Corolla"], a: 1 },
  { q: "The female reproductive organ of a flower is", o: ["Androecium", "Calyx", "Gynoecium", "Corolla"], a: 2 },
  { q: "A stamen consists of", o: ["Anther and filament", "Anther and style", "Filament and ovary", "Ovary and stigma"], a: 0 },
  { q: "Pollen grains are produced in", o: ["Ovary", "Style", "Anther", "Stigma"], a: 2 },
  { q: "The outermost layer of pollen grain is called", o: ["Intine", "Exine", "Nucellus", "Tegmen"], a: 1 },
  { q: "Sporopollenin is present in", o: ["Intine", "Exine", "Integument", "Nucellus"], a: 1 },
  { q: "The main function of tapetum is to", o: ["Provide nutrition to pollen", "Form pollen tube", "Form ovule", "Produce stigma"], a: 0 },
  { q: "Pollen grains develop from", o: ["Microspore mother cells", "Megaspore mother cells", "Zygote", "Ovule"], a: 0 },
  { q: "Which type of cell division produces pollen grains?", o: ["Mitosis", "Meiosis", "Amitosis", "Binary fission"], a: 1 },
  { q: "The female gametophyte is called", o: ["Ovule", "Embryo sac", "Nucellus", "Ovary"], a: 1 },
  { q: "The functional megaspore in angiosperms is", o: ["One", "Two", "Three", "Four"], a: 0 },
  { q: "The most common type of embryo sac development is", o: ["Bisporic", "Tetrasporic", "Monosporic", "Polysporic"], a: 2 },
  { q: "A typical angiosperm embryo sac is", o: ["6-celled, 6-nucleate", "7-celled, 8-nucleate", "8-celled, 7-nucleate", "8-celled, 8-nucleate"], a: 1 },
  { q: "Synergids are present at", o: ["Chalazal end", "Micropylar end", "Central region", "Ovary wall"], a: 1 },
  { q: "Antipodal cells are present at", o: ["Micropylar end", "Chalazal end", "Central cell", "Ovary"], a: 1 },
  { q: "The pollen tube enters the ovule through", o: ["Chalaza", "Funiculus", "Micropyle", "Integument"], a: 2 },
  { q: "Pollination is the transfer of pollen grains from", o: ["Anther to stigma", "Anther to ovule", "Stigma to ovary", "Ovule to ovary"], a: 0 },
  { q: "Self-pollination occurs in", o: ["Unisexual flowers", "Bisexual flowers", "Dioecious plants", "Wind-pollinated plants"], a: 1 },
  { q: "Cross-pollination occurs between", o: ["Same flower", "Same plant", "Different plants of same species", "Different species"], a: 2 },
  { q: "Double fertilisation is characteristic of", o: ["Gymnosperms", "Bryophytes", "Angiosperms", "Pteridophytes"], a: 2 },
  { q: "One male gamete fuses with egg to form", o: ["Endosperm", "Zygote", "Embryo", "Synergid"], a: 1 },
  { q: "Triple fusion results in formation of", o: ["Zygote", "Embryo", "Endosperm", "Ovule"], a: 2 },
  { q: "Endosperm in angiosperms is generally", o: ["Diploid", "Haploid", "Triploid", "Tetraploid"], a: 2 },
  { q: "The edible part of coconut is", o: ["Testa", "Endosperm", "Embryo", "Mesocarp"], a: 1 },
  { q: "After fertilisation, ovule develops into", o: ["Fruit", "Seed", "Ovary", "Embryo sac"], a: 1 },
  { q: "Ovary develops into", o: ["Seed", "Embryo", "Fruit", "Endosperm"], a: 2 },
  { q: "The outer covering of seed is formed from", o: ["Nucellus", "Integuments", "Endosperm", "Ovary wall"], a: 1 },
  { q: "Polyembryony means", o: ["One embryo in one seed", "No embryo", "More than one embryo in a seed", "One embryo in many seeds"], a: 2 },
  { q: "Apomixis is", o: ["Sexual reproduction", "Vegetative reproduction", "Asexual seed formation", "Double fertilisation"], a: 2 },
  { q: "Cleistogamous flowers ensure", o: ["Cross-pollination", "Self-pollination", "Wind pollination", "Insect pollination"], a: 1 },
  { q: "Agents of pollination include", o: ["Wind", "Water", "Insects", "All of these"], a: 3 },
  { q: "Wind pollinated flowers usually have", o: ["Bright petals", "Sticky pollen", "Large stigma", "Nectar"], a: 2 },
  { q: "Insect-pollinated flowers are generally", o: ["Dull and small", "Without nectar", "Bright and fragrant", "Without petals"], a: 2 },
  { q: "Fruit formed without fertilisation is called", o: ["True fruit", "False fruit", "Parthenocarpic fruit", "Aggregate fruit"], a: 2 }
];
