const questions = [
  { q: "Primary sex organ in males is", o: ["Penis","Testis","Scrotum","Prostate"], a: 1 },
  { q: "Primary sex organ in females is", o: ["Uterus","Ovary","Vagina","Cervix"], a: 1 },
  { q: "Functional unit of testis is", o: ["Epididymis","Leydig cells","Seminiferous tubules","Vas deferens"], a: 2 },
  { q: "Sertoli cells are found in", o: ["Epididymis","Seminiferous tubules","Prostate","Vas deferens"], a: 1 },
  { q: "Leydig cells secrete", o: ["Estrogen","Progesterone","Testosterone","FSH"], a: 2 },
  { q: "Spermatogenesis occurs in", o: ["Epididymis","Vas deferens","Seminiferous tubules","Prostate gland"], a: 2 },
  { q: "Spermatogenesis starts at", o: ["Birth","Puberty","Adolescence end","Fertilisation"], a: 1 },
  { q: "Hormone stimulating spermatogenesis is", o: ["LH","FSH","Estrogen","Prolactin"], a: 1 },
  { q: "Spermiogenesis is", o: ["Formation of spermatocytes","Formation of spermatids","Conversion of spermatids into sperm","Release of sperms"], a: 2 },
  { q: "Release of sperms from seminiferous tubules is called", o: ["Ejaculation","Spermiation","Fertilisation","Copulation"], a: 1 },

  { q: "Sperms mature and are stored in", o: ["Vas deferens","Urethra","Epididymis","Testis"], a: 2 },
  { q: "Acrosome of sperm contains", o: ["DNA","RNA","Enzymes","Mitochondria"], a: 2 },
  { q: "Middle piece of sperm contains", o: ["Enzymes","Nucleus","Mitochondria","Ribosomes"], a: 2 },
  { q: "Female gamete is called", o: ["Zygote","Ovum","Oocyte","Embryo"], a: 1 },
  { q: "Oogenesis starts", o: ["At puberty","At birth","During embryonic development","After fertilisation"], a: 2 },
  { q: "Primary oocytes are arrested in", o: ["Metaphase I","Prophase I","Metaphase II","Telophase I"], a: 1 },
  { q: "Number of ova released per menstrual cycle is", o: ["One","Two","Four","Many"], a: 0 },
  { q: "Average menstrual cycle duration is", o: ["21 days","25 days","28 days","35 days"], a: 2 },
  { q: "Ovulation occurs around", o: ["7th day","10th day","14th day","21st day"], a: 2 },
  { q: "Hormone responsible for ovulation is", o: ["FSH","Estrogen","LH","Progesterone"], a: 2 },

  { q: "Corpus luteum is formed from", o: ["Primary follicle","Secondary follicle","Tertiary follicle","Graafian follicle"], a: 3 },
  { q: "Corpus luteum secretes", o: ["Estrogen","Progesterone","FSH","LH"], a: 1 },
  { q: "Menstrual phase occurs due to", o: ["Increase in estrogen","Increase in progesterone","Decrease in estrogen and progesterone","Increase in LH"], a: 2 },
  { q: "Menstrual cycle occurs from", o: ["Birth to death","Puberty to menopause","Puberty to pregnancy","Adolescence to old age"], a: 1 },
  { q: "Fertilisation in humans occurs in", o: ["Ovary","Uterus","Cervix","Ampullary–isthmic junction"], a: 3 },
  { q: "Implantation occurs in", o: ["Ovary","Fallopian tube","Uterus","Cervix"], a: 2 },
  { q: "Human placenta is", o: ["Endotheliochorial","Epitheliochorial","Hemochorial","Syndesmochorial"], a: 2 },
  { q: "Hormone detected in pregnancy test is", o: ["Progesterone","Estrogen","hCG","LH"], a: 2 },
  { q: "Placenta secretes", o: ["hCG","Progesterone","Estrogen","All of these"], a: 3 },
  { q: "Duration of human pregnancy is about", o: ["240 days","260 days","280 days","300 days"], a: 2 },

  { q: "Umbilical cord has", o: ["One artery and one vein","Two veins and one artery","Two arteries and one vein","Only veins"], a: 2 },
  { q: "Colostrum is rich in", o: ["Fats","Vitamins","Antibodies","Minerals"], a: 2 },
  { q: "Parturition is controlled by", o: ["Estrogen","Progesterone","Oxytocin","Prolactin"], a: 2 },
  { q: "Hormone for milk production is", o: ["Oxytocin","Estrogen","Prolactin","Progesterone"], a: 2 },
  { q: "Hormone for milk ejection is", o: ["Prolactin","Estrogen","Oxytocin","LH"], a: 2 },
  { q: "First stage of labour involves", o: ["Delivery of baby","Cervical dilation","Placenta removal","Milk secretion"], a: 1 },
  { q: "Second stage of labour involves", o: ["Cervical dilation","Placenta expulsion","Delivery of baby","Lactation"], a: 2 },
  { q: "Third stage of labour involves", o: ["Baby delivery","Cervix dilation","Placenta expulsion","Milk secretion"], a: 2 },
  { q: "Zona pellucida surrounds", o: ["Sperm","Ovum","Zygote","Embryo"], a: 1 },
  { q: "Cleavage divisions are", o: ["Meiotic","Mitotic","Reductional","Amitotic"], a: 1 },

  { q: "Morula stage has", o: ["2 cells","4 cells","8–16 cells","32–64 cells"], a: 2 },
  { q: "Blastocyst consists of", o: ["Inner cell mass only","Trophoblast only","Both trophoblast and inner cell mass","Placenta"], a: 2 },
  { q: "Trophoblast helps in", o: ["Embryo formation","Placenta formation","Organogenesis","Fertilisation"], a: 1 },
  { q: "Inner cell mass forms", o: ["Placenta","Uterine wall","Embryo","Umbilical cord"], a: 2 },
  { q: "Gestation period is counted from", o: ["Ovulation","Fertilisation","Implantation","Last menstrual period"], a: 3 },
  { q: "Mammary glands are modified", o: ["Sebaceous glands","Sweat glands","Endocrine glands","Salivary glands"], a: 1 },
  { q: "Relaxin hormone helps in", o: ["Milk secretion","Ovulation","Cervical dilation","Spermatogenesis"], a: 2 },
  { q: "Cervix connects uterus to", o: ["Ovary","Fallopian tube","Vagina","Vulva"], a: 2 },
  { q: "Menopause occurs due to", o: ["Increase in estrogen","Increase in progesterone","Cessation of ovarian function","Increase in FSH"], a: 2 },
  { q: "Average age of menopause is", o: ["30–35","35–40","45–50","55–60"], a: 2 },

  { q: "Fertile period in menstrual cycle is around", o: ["Day 1–5","Day 6–10","Day 12–16","Day 20–25"], a: 2 },
  { q: "Estrogen is secreted mainly by", o: ["Corpus luteum","Graafian follicle","Pituitary gland","Placenta only"], a: 1 },
  { q: "Progesterone prepares uterus for", o: ["Ovulation","Menstruation","Implantation","Parturition"], a: 2 },
  { q: "hCG maintains", o: ["Graafian follicle","Corpus luteum","Ovulation","Menstruation"], a: 1 },
  { q: "Site of sperm deposition during copulation is", o: ["Cervix","Uterus","Vagina","Ovary"], a: 2 },
  { q: "Hymen partially covers", o: ["Cervix","Urethra","Vaginal opening","Uterus"], a: 2 },
  { q: "Female reproductive cycle stops at", o: ["Puberty","Pregnancy","Menopause","Lactation"], a: 2 },
  { q: "Secondary oocyte is released during", o: ["Menstrual phase","Follicular phase","Ovulation","Luteal phase"], a: 2 },
  { q: "Secondary oocyte is arrested at", o: ["Prophase I","Metaphase I","Prophase II","Metaphase II"], a: 3 },
  { q: "Completion of meiosis II in oocyte occurs after", o: ["Ovulation","Menstruation","Fertilisation","Implantation"], a: 2 }
];
