const questions = [
  { q: "Mendel is known as the father of genetics because of his work on", o: ["Drosophila","Pea plant","Maize","Wheat"], a: 1 },
  { q: "Mendel conducted his experiments on", o: ["Garden pea","Wild pea","Sweet pea","Chickpea"], a: 0 },
  { q: "The scientific name of pea plant is", o: ["Pisum sativum","Lathyrus odoratus","Phaseolus vulgaris","Cicer arietinum"], a: 0 },
  { q: "Mendel selected pea plant because", o: ["It has bisexual flowers","Short life cycle","Easy cultivation","All of these"], a: 3 },
  { q: "A true-breeding plant is one which", o: ["Produces hybrids","Produces same trait generation after generation","Produces sterile seeds","Shows variation"], a: 1 },

  { q: "The observable characteristics of an organism are called", o: ["Genotype","Phenotype","Alleles","Genes"], a: 1 },
  { q: "Genetic makeup of an organism is called", o: ["Phenotype","Genotype","Allele","Chromosome"], a: 1 },
  { q: "The alternative forms of a gene are called", o: ["Traits","Phenotypes","Alleles","Loci"], a: 2 },
  { q: "Mendel studied how many pairs of contrasting traits?", o: ["5","6","7","8"], a: 2 },
  { q: "The law of dominance states that", o: ["Both alleles express equally","One allele masks the other","Genes segregate","Genes assort independently"], a: 1 },

  { q: "The trait that expresses in F₁ generation is", o: ["Recessive","Dominant","Lethal","Incomplete"], a: 1 },
  { q: "The law of segregation is also called", o: ["Law of purity of gametes","Law of dominance","Law of inheritance","Law of linkage"], a: 0 },
  { q: "During gamete formation, alleles", o: ["Mix together","Remain together","Separate","Mutate"], a: 2 },
  { q: "A monohybrid cross involves", o: ["One trait","Two traits","Three traits","Many traits"], a: 0 },
  { q: "Phenotypic ratio of monohybrid cross is", o: ["1 : 2 : 1","2 : 1","3 : 1","9 : 3 : 3 : 1"], a: 2 },

  { q: "Genotypic ratio of monohybrid cross is", o: ["3 : 1","1 : 2 : 1","9 : 3 : 3 : 1","2 : 1"], a: 1 },
  { q: "A dihybrid cross involves", o: ["One gene","Two genes","Three genes","Many genes"], a: 1 },
  { q: "Phenotypic ratio of dihybrid cross is", o: ["3 : 1","1 : 2 : 1","9 : 3 : 3 : 1","1 : 1 : 1 : 1"], a: 2 },
  { q: "Law of independent assortment is applicable to", o: ["Linked genes","Alleles of same gene","Genes on different chromosomes","Sex-linked genes"], a: 2 },
  { q: "Test cross is a cross between", o: ["Two hybrids","Hybrid and recessive parent","Two dominant parents","Two recessive parents"], a: 1 },

  { q: "Test cross helps to determine", o: ["Phenotype","Dominance","Genotype","Mutation"], a: 2 },
  { q: "In incomplete dominance, F₁ shows", o: ["Dominant trait","Recessive trait","Intermediate trait","Both traits"], a: 2 },
  { q: "Example of incomplete dominance is seen in", o: ["Pea plant","Snapdragon","Maize","Drosophila"], a: 1 },
  { q: "Phenotypic ratio in incomplete dominance is", o: ["3 : 1","1 : 2 : 1","9 : 3 : 3 : 1","1 : 1"], a: 1 },
  { q: "In co-dominance", o: ["One allele dominates","Intermediate trait is formed","Both alleles express equally","One allele mutates"], a: 2 },

  { q: "Example of co-dominance is", o: ["Flower colour in pea","Snapdragon flower","ABO blood group","Height in humans"], a: 2 },
  { q: "Blood group AB shows", o: ["Dominance","Recessiveness","Co-dominance","Incomplete dominance"], a: 2 },
  { q: "Gene for blood group is located on", o: ["X chromosome","Y chromosome","Autosome","Mitochondria"], a: 2 },
  { q: "Multiple alleles are", o: ["Two alleles only","More than two alleles of a gene","Multiple genes","Linked genes"], a: 1 },
  { q: "ABO blood group has how many alleles?", o: ["2","3","4","5"], a: 1 },

  { q: "Polygenic inheritance controls", o: ["Single trait","Discontinuous variation","Continuous variation","Lethal traits"], a: 2 },
  { q: "Human height is an example of", o: ["Monogenic trait","Polygenic trait","Sex-linked trait","Mutation"], a: 1 },
  { q: "Chromosomal theory of inheritance was proposed by", o: ["Mendel","Darwin","Sutton and Boveri","Morgan"], a: 2 },
  { q: "Genes are located on", o: ["Ribosomes","Chromosomes","Cytoplasm","Mitochondria only"], a: 1 },
  { q: "Linkage was discovered by", o: ["Mendel","Morgan","Sutton","Watson"], a: 1 },

  { q: "Linked genes are those which", o: ["Assort independently","Are present on same chromosome","Are alleles","Are sex-linked"], a: 1 },
  { q: "Crossing over occurs during", o: ["Prophase I of meiosis","Metaphase I","Anaphase I","Telophase I"], a: 0 },
  { q: "Crossing over results in", o: ["Variation","No variation","Mutation only","Sterility"], a: 0 },
  { q: "Sex-linked inheritance is related to", o: ["Autosomes","X chromosome","Y chromosome","Both B and C"], a: 3 },
  { q: "Colour blindness is a", o: ["Autosomal dominant disorder","Autosomal recessive disorder","X-linked recessive disorder","Y-linked disorder"], a: 2 },

  { q: "Haemophilia is transmitted by", o: ["Autosomes","X chromosome","Y chromosome","Mitochondria"], a: 1 },
  { q: "A carrier female for haemophilia is", o: ["Affected","Normal","Heterozygous","Homozygous"], a: 2 },
  { q: "Y-linked traits are passed from", o: ["Mother to son","Father to daughter","Father to son","Mother to daughter"], a: 2 },
  { q: "Mutation is defined as", o: ["Sudden heritable change","Gradual change","Non-heritable change","Environmental change"], a: 0 },
  { q: "Mutations can be induced by", o: ["X-rays","Chemicals","UV rays","All of these"], a: 3 },

  { q: "Sickle cell anaemia is caused due to", o: ["Deletion","Substitution","Inversion","Duplication"], a: 1 },
  { q: "Sickle cell anaemia is", o: ["Dominant disorder","Recessive disorder","Sex-linked disorder","Polygenic disorder"], a: 1 },
  { q: "Phenylketonuria is", o: ["Dominant","Recessive","X-linked","Y-linked"], a: 1 },
  { q: "Pleiotropy means", o: ["One gene affects many traits","Many genes affect one trait","One trait affects many genes","No effect"], a: 0 },
  { q: "Lethal genes cause", o: ["Extra growth","No effect","Death","Variation"], a: 2 },

  { q: "In pedigree analysis, square represents", o: ["Female","Male","Carrier","Affected"], a: 1 },
  { q: "Circle in pedigree represents", o: ["Male","Female","Affected male","Carrier male"], a: 1 },
  { q: "Shaded symbol in pedigree shows", o: ["Normal individual","Carrier","Affected individual","Dead individual"], a: 2 },
  { q: "Mendelian disorders include", o: ["Thalassemia","Sickle cell anaemia","Phenylketonuria","All of these"], a: 3 },
  { q: "Thalassemia affects", o: ["Blood clotting","Hemoglobin synthesis","Platelets","WBCs"], a: 1 },

  { q: "Autosomal recessive disorders appear", o: ["In every generation","Only in males","When both alleles are recessive","Only in females"], a: 2 },
  { q: "Test cross ratio of dihybrid cross is", o: ["9 : 3 : 3 : 1","1 : 1","1 : 1 : 1 : 1","3 : 1"], a: 2 },
  { q: "Morgan worked on", o: ["Pea plant","Maize","Drosophila","Mouse"], a: 2 },
  { q: "The position of gene on chromosome is called", o: ["Allele","Locus","Chromatid","Centromere"], a: 1 },
  { q: "Recombination frequency is proportional to", o: ["Gene linkage","Distance between genes","Dominance","Mutation"], a: 1 },

  { q: "More the distance between genes,", o: ["Less recombination","No recombination","More recombination","No effect"], a: 2 },
  { q: "Mendel’s laws are applicable to", o: ["All organisms","Only plants","Organisms showing sexual reproduction","Bacteria"], a: 2 },
  { q: "The physical basis of inheritance is", o: ["DNA","RNA","Protein","Lipid"], a: 0 },
  { q: "Gene is a segment of", o: ["RNA","DNA","Protein","Lipid"], a: 1 },
  { q: "Mutation that affects a single base pair is called", o: ["Chromosomal mutation","Gene mutation","Genome mutation","Structural mutation"], a: 1 },

  { q: "Sex determination in humans is based on", o: ["Autosomes","X chromosome","Y chromosome","Both X and Y chromosomes"], a: 3 },
  { q: "Human female has chromosomes", o: ["XX","XY","XO","YY"], a: 0 },
  { q: "Human male has chromosomes", o: ["XX","XY","XO","YY"], a: 1 },
  { q: "A heterozygous individual contains", o: ["Identical alleles","No alleles","Different alleles","Lethal alleles"], a: 2 },
  { q: "Homozygous recessive genotype is represented by", o: ["AA","Aa","aa","A–"], a: 2 },

  { q: "Mendel’s experimental success was due to", o: ["Statistical analysis","Clear contrasting traits","Large sample size","All of these"], a: 3 },
  { q: "The inheritance pattern where traits appear in alternate generations is", o: ["Dominant","Recessive","Polygenic","Co-dominant"], a: 1 },
  { q: "Gene interaction where two genes affect same trait is", o: ["Pleiotropy","Epistasis","Mutation","Linkage"], a: 1 },
  { q: "Complementary genes produce ratio", o: ["9 : 7","15 : 1","13 : 3","12 : 3 : 1"], a: 0 },
  { q: "Epistasis modifies Mendelian ratios in", o: ["Monohybrid cross","Dihybrid cross","Test cross","Back cross"], a: 1 },

  { q: "The smallest unit of inheritance is", o: ["Chromosome","Gene","DNA","Nucleotide"], a: 1 },
  { q: "Linkage reduces", o: ["Recombination","Variation","Independent assortment","All of these"], a: 3 },
  { q: "Morgan’s experiment supported", o: ["Mendel’s law only","Chromosomal theory","Mutation theory","Natural selection"], a: 1 },
  { q: "Human blood group O genotype is", o: ["IAIB","IAi","IBi","ii"], a: 3 },
  { q: "The universal donor blood group is", o: ["A","B","AB","O"], a: 3 },

  { q: "The universal recipient blood group is", o: ["A","B","AB","O"], a: 2 },
  { q: "Sex-linked traits show criss-cross inheritance in", o: ["Autosomes","Females","Males","X-linked traits"], a: 3 },
  { q: "Morgan observed more parental combinations due to", o: ["Independent assortment","Mutation","Linkage","Crossing over"], a: 2 },
  { q: "Genetic variation arises due to", o: ["Mutation","Recombination","Sexual reproduction","All of these"], a: 3 },
  { q: "The first step of inheritance is", o: ["Fertilisation","Gamete formation","Zygote formation","Embryo formation"], a: 1 },

  { q: "Chromosomal disorders are caused due to", o: ["Gene mutation","Numerical changes","Structural changes","Both B and C"], a: 3 },
  { q: "Down syndrome is caused by", o: ["Trisomy 21","Trisomy 18","Monosomy X","XXY"], a: 0 },
  { q: "Turner syndrome genotype is", o: ["XXY","XO","XXX","XYY"], a: 1 },
  { q: "Klinefelter syndrome genotype is", o: ["XO","XX","XXY","XYY"], a: 2 },
  { q: "Variation is important because it", o: ["Causes disease","Reduces survival","Helps in evolution","Stops inheritance"], a: 2 }
];
